export const FAQS = [
  { q: 'What technologies do you use for web development?',   a: 'We primarily build with Next.js, React, and TypeScript, delivering fast, SEO-friendly sites. For backends we use Node.js, PostgreSQL, or headless CMS platforms based on your requirements.' },
  { q: 'How long does a typical website project take?',        a: 'A standard corporate website takes 3 to 5 weeks from kickoff to launch. E-commerce platforms or web apps with complex features typically take 6 to 10 weeks. We share a detailed timeline after the discovery phase, so you know exactly what to expect and when.' },
  { q: 'Will my website be mobile-friendly and fast?',         a: 'Absolutely. Every website we build is fully responsive and optimized for Core Web Vitals, targeting sub-2-second load times and 90+ Lighthouse scores.' },
  { q: 'Do you provide ongoing maintenance and updates?',      a: 'Yes. We offer monthly maintenance retainers covering security updates, content changes, performance monitoring, and feature enhancements.' },
  { q: 'Can you redesign my existing website?',               a: 'Yes, we handle full redesigns and migrations. We audit your current site first and propose a strategy that preserves your SEO equity while improving performance and design.' },
  { q: 'Do you build React web applications, not just marketing websites?', a: 'Yes. Beyond corporate sites, we build React and Next.js web applications with authentication, dashboards, and custom business logic for clients who need a functioning product, not just a brochure site.' },
  { q: 'Do you build e-commerce websites?',                   a: 'Yes, we build custom e-commerce platforms as well as headless commerce setups on Shopify and similar platforms. We handle product catalogs, payment gateways, and checkout flows optimized for conversion, not just a generic template.' },
  { q: 'How much does a custom website cost?',                a: 'A standard corporate website typically starts around $2,500 to $5,000. E-commerce platforms or web apps with custom features usually run $6,000 to $15,000 and up depending on complexity. We give you a fixed quote after discovery, not a vague range.' },
  { q: 'How long does website development take?',            a: 'It depends on the type of site: a landing page can ship in 1 to 2 weeks, a standard corporate site in 3 to 5 weeks, and an e-commerce platform or web app in 6 to 10 weeks. The biggest swing factor is how many custom features and integrations are involved, not the number of pages.' },
  { q: 'What is the best tech stack for a business website in 2026?', a: 'For most businesses, Next.js with React and TypeScript is the strongest choice: fast page loads, strong SEO out of the box, and a component structure that scales as you add features. We pair it with a headless CMS when clients need to edit content without a developer.' },
]
