export const FAQS = [
  { q: 'How long does it take to build a SaaS product?',          a: 'A focused MVP with core features takes 6 to 10 weeks. A full-featured product with billing, roles, integrations, and an admin dashboard typically takes 12 to 20 weeks. We share a detailed milestone plan after discovery, so you always know where the project stands.' },
  { q: 'What tech stack do you use for SaaS development?',        a: 'We primarily build with Next.js for the frontend, Node.js or Python for the backend, PostgreSQL for data, and AWS or Vercel for infrastructure. We adapt to your existing stack if needed.' },
  { q: 'Can you help with the pricing and monetization model?',   a: 'Yes. We have built SaaS products across subscription, usage-based, freemium, and lifetime deal models. We advise on what works for your market and implement the billing infrastructure accordingly.' },
  { q: 'What happens after the MVP launches?',                    a: 'We offer ongoing sprint-based development for new features, performance optimization, and integrations. We also offer managed hosting and SLA-backed support so you\'re never alone after launch.' },
  { q: 'Who owns the source code?',                              a: 'You own 100% of the source code, IP, and infrastructure. Everything we build is transferred upon project completion. We can also hand over to your internal developers at any stage.' },
  { q: 'How much does it cost to build a SaaS product?',          a: 'A focused MVP typically runs into six figures (INR), depending on feature scope, integrations, and design complexity. A full-featured product with billing, multi-tenancy, and an admin dashboard costs more. We give you a fixed quote after discovery, once we know your exact feature list.' },
  { q: 'How long does it take to build a SaaS MVP?',              a: 'Most SaaS MVPs take 6 to 10 weeks from kickoff to a working product your first users can log into. Timelines stretch if you need complex integrations, SSO, or industry-specific compliance work built in from day one.' },
  { q: 'What tech stack is best for a SaaS product in 2026?',      a: 'For most SaaS products we still recommend Next.js on the frontend, Node.js or Python on the backend, and PostgreSQL for the database, deployed on AWS or Vercel. It is a stack that scales cleanly from a first MVP to a multi-tenant product with heavy traffic, without a rewrite.' },
  { q: 'Can you build a multi-tenant SaaS from scratch?',          a: 'Yes, multi-tenant architecture is one of our core specialties. We design proper data isolation between tenants from the start, whether that means a shared database with tenant scoping or separate schemas, based on your security and scale requirements.' },
  { q: 'Do you handle SaaS billing integration?',                  a: 'Yes. We integrate Stripe or Razorpay for subscription billing, including plan management, trial periods, proration, invoicing, and dunning workflows for failed payments, so billing runs on autopilot from launch.' },
]
