export const FAQS = [
  { q: 'Should I build a native or cross-platform app?',         a: 'It depends on your needs and budget. React Native / Flutter gives ~90% cost savings with excellent performance. We recommend native (Swift/Kotlin) only when you need deep platform-specific features like AR or complex custom animations.' },
  { q: 'How long does it take to build a mobile app?',           a: 'A basic MVP takes 6 to 10 weeks to build and launch. A full-featured app with deeper integrations and custom features typically takes 12 to 20 weeks. We give you a precise timeline after the discovery workshop, once we understand exactly what you are trying to build.' },
  { q: 'Do you handle App Store and Play Store submissions?',    a: 'Yes, we handle the entire submission process including App Store Connect setup, screenshots, descriptions, compliance review, and resubmissions if needed.' },
  { q: 'Will my app work offline?',                             a: 'We can implement offline-first architecture with local data sync so your app remains usable without an internet connection. This is scoped during the discovery phase.' },
  { q: 'Do you provide post-launch support?',                   a: 'Yes. We offer support retainers that cover bug fixes, OS update compatibility, performance monitoring, and new feature development after launch.' },
  { q: 'Do you build with React Native as a dedicated cross-platform team?', a: 'Yes. React Native is one of our primary cross-platform stacks alongside Flutter, and most of our mobile team works in it daily. It lets us ship a single codebase to iOS and Android while still reaching native performance for the vast majority of use cases.' },
  { q: 'What factors affect mobile app development cost?',      a: 'The biggest drivers are the number of screens, backend complexity, third-party integrations (payments, maps, CRMs), and whether you go native or cross-platform. Custom animations, offline sync, and real-time features also add to the estimate, which is why we quote after a discovery workshop rather than off a flat rate card.' },
  { q: 'How much does it cost to build a mobile app?',          a: 'Costs range from roughly $8,000 to $15,000 for a focused MVP up to $30,000 or more for a full-featured app with deep integrations. React Native or Flutter typically comes in well below an equivalent native build for the same feature set.' },
  { q: 'How long does it take to launch a cross-platform app on both the App Store and Play Store?', a: 'Build time is usually 6 to 20 weeks depending on scope, and we add roughly 1 to 2 weeks on top for App Store and Play Store review once submissions go in. Apple review can occasionally take longer for first-time developer accounts, which we account for in your launch plan.' },
  { q: 'What is the cost difference between native and cross-platform app development?', a: 'Native development (separate Swift and Kotlin codebases) typically costs noticeably more since you are essentially building two apps. React Native or Flutter delivers roughly 90% cost savings by sharing one codebase across iOS and Android, with native reserved for cases that genuinely need platform-specific performance like AR.' },
]
