import { NewsSource } from './types';

export const NEWS_SOURCES: NewsSource[] = [

  // ─── OFFICIAL AI COMPANY BLOGS ────────────────────────────────────────────
  { name: 'OpenAI News',       url: 'https://openai.com/blog/rss.xml',                               type: 'rss', category: 'company_blog', company: 'OpenAI' },
  { name: 'Anthropic Blog',    url: 'https://www.anthropic.com/news/rss',                            type: 'rss', category: 'company_blog', company: 'Anthropic' },
  { name: 'Google AI Blog',    url: 'https://blog.google/technology/ai/rss/',                        type: 'rss', category: 'company_blog', company: 'Google' },
  { name: 'Google DeepMind',   url: 'https://deepmind.google/blog/rss.xml',                          type: 'rss', category: 'company_blog', company: 'Google DeepMind' },
  { name: 'Meta AI Blog',      url: 'https://about.fb.com/news/feed/',                               type: 'rss', category: 'company_blog', company: 'Meta' },
  { name: 'Microsoft AI Blog', url: 'https://news.microsoft.com/ai/feed/',                           type: 'rss', category: 'company_blog', company: 'Microsoft' },
  { name: 'NVIDIA Blog',       url: 'https://blogs.nvidia.com/feed/',                                type: 'rss', category: 'company_blog', company: 'NVIDIA' },
  { name: 'HuggingFace Blog',  url: 'https://huggingface.co/blog/feed.xml',                          type: 'rss', category: 'company_blog', company: 'HuggingFace' },
  { name: 'Mistral AI',        url: 'https://mistral.ai/fr/news/feed/',                              type: 'rss', category: 'company_blog', company: 'Mistral' },
  { name: 'Cohere Blog',       url: 'https://cohere.com/blog/rss/',                                  type: 'rss', category: 'company_blog', company: 'Cohere' },
  { name: 'Stability AI',      url: 'https://stability.ai/news/rss',                                 type: 'rss', category: 'company_blog', company: 'Stability AI' },
  { name: 'Perplexity Blog',   url: 'https://blog.perplexity.ai/rss',                                type: 'rss', category: 'company_blog', company: 'Perplexity' },
  { name: 'Amazon AWS AI',     url: 'https://aws.amazon.com/blogs/machine-learning/feed/',           type: 'rss', category: 'company_blog', company: 'Amazon' },
  { name: 'xAI Blog',         url: 'https://x.ai/blog/rss.xml',                                    type: 'rss', category: 'company_blog', company: 'xAI' },
  { name: 'ElevenLabs Blog',   url: 'https://elevenlabs.io/blog/rss',                                type: 'rss', category: 'company_blog', company: 'ElevenLabs' },
  { name: 'Runway Blog',       url: 'https://runwayml.com/news/rss',                                 type: 'rss', category: 'company_blog', company: 'Runway' },
  { name: 'Groq News',         url: 'https://groq.com/news/rss',                                     type: 'rss', category: 'company_blog', company: 'Groq' },
  { name: 'Cerebras Blog',     url: 'https://www.cerebras.ai/blog/rss',                              type: 'rss', category: 'company_blog', company: 'Cerebras' },
  { name: 'Character AI Blog', url: 'https://blog.character.ai/feed/',                               type: 'rss', category: 'company_blog', company: 'Character AI' },
  { name: 'Midjourney Updates',url: 'https://updates.midjourney.com/feed',                           type: 'rss', category: 'company_blog', company: 'Midjourney' },
  { name: 'Google Cloud AI',   url: 'https://cloud.google.com/blog/products/ai-machine-learning/rss/', type: 'rss', category: 'company_blog', company: 'Google Cloud' },
  { name: 'Azure AI Blog',     url: 'https://azure.microsoft.com/en-us/blog/feed/',                  type: 'rss', category: 'company_blog', company: 'Microsoft Azure' },
  { name: 'IBM Newsroom',      url: 'https://newsroom.ibm.com/rss/news-releases.htm',                type: 'rss', category: 'company_blog', company: 'IBM' },

  // ─── AI NEWS WEBSITES ─────────────────────────────────────────────────────
  { name: 'TechCrunch AI',          url: 'https://techcrunch.com/category/artificial-intelligence/feed/',  type: 'rss', category: 'news' },
  { name: 'VentureBeat AI',         url: 'https://venturebeat.com/ai/feed/',                               type: 'rss', category: 'news' },
  { name: 'VentureBeat Enterprise', url: 'https://venturebeat.com/category/enterprise-ai/feed/',           type: 'rss', category: 'news' },
  { name: 'The Verge AI',           url: 'https://www.theverge.com/ai-artificial-intelligence/rss/index.xml', type: 'rss', category: 'news' },
  { name: 'Wired AI',               url: 'https://www.wired.com/feed/tag/artificial-intelligence/rss',     type: 'rss', category: 'news' },
  { name: 'MIT Technology Review',  url: 'https://www.technologyreview.com/feed/',                         type: 'rss', category: 'news' },
  { name: 'Ars Technica AI',        url: 'https://arstechnica.com/tag/artificial-intelligence/feed/',      type: 'rss', category: 'news' },
  { name: 'ZDNet AI',               url: 'https://www.zdnet.com/topic/artificial-intelligence/rss.xml',    type: 'rss', category: 'news' },
  { name: 'The Decoder',            url: 'https://the-decoder.com/feed/',                                  type: 'rss', category: 'news' },
  { name: 'MarkTechPost',           url: 'https://www.marktechpost.com/feed/',                             type: 'rss', category: 'news' },
  { name: 'Analytics India Mag',    url: 'https://analyticsindiamag.com/feed/',                            type: 'rss', category: 'news' },
  { name: 'Unite.AI',               url: 'https://www.unite.ai/feed/',                                     type: 'rss', category: 'news' },
  { name: 'AI Business',            url: 'https://aibusiness.com/rss',                                     type: 'rss', category: 'news' },
  { name: 'Synced Review',          url: 'https://syncedreview.com/feed/',                                 type: 'rss', category: 'news' },
  { name: 'Towards AI',             url: 'https://towardsai.net/feed/',                                    type: 'rss', category: 'news' },
  { name: 'KDnuggets',              url: 'https://www.kdnuggets.com/feed',                                 type: 'rss', category: 'news' },
  { name: 'InfoQ AI',               url: 'https://feed.infoq.com/ai-ml-data-eng/',                        type: 'rss', category: 'news' },
  { name: 'AI Magazine',            url: 'https://aimagazine.com/rss',                                     type: 'rss', category: 'news' },
  { name: 'ML Mastery',             url: 'https://machinelearningmastery.com/blog/feed/',                  type: 'rss', category: 'news' },
  { name: 'Towards Data Science',   url: 'https://towardsdatascience.com/feed',                            type: 'rss', category: 'news' },
  { name: 'The Register AI',        url: 'https://www.theregister.com/software/ai_ml/headlines.atom',     type: 'rss', category: 'news' },
  { name: 'SiliconANGLE',          url: 'https://siliconangle.com/feed/',                                 type: 'rss', category: 'news' },
  { name: 'IEEE Spectrum AI',       url: 'https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss', type: 'rss', category: 'news' },
  { name: 'Fast Company Tech',      url: 'https://www.fastcompany.com/technology/rss',                     type: 'rss', category: 'news' },
  { name: 'CNBC AI',                url: 'https://www.cnbc.com/id/100899163/device/rss/rss.html',          type: 'rss', category: 'news' },
  { name: 'Reuters Technology',     url: 'https://feeds.reuters.com/reuters/technologyNews',               type: 'rss', category: 'news' },
  { name: 'Lobsters',               url: 'https://lobste.rs/rss',                                          type: 'rss', category: 'news' },
  { name: 'Slashdot',              url: 'https://rss.slashdot.org/Slashdot/slashdotMain',                 type: 'rss', category: 'news' },
  { name: 'Last Week in AI',        url: 'https://lastweekin.ai/feed',                                     type: 'rss', category: 'news' },
  { name: 'Future Tools',           url: 'https://futuretools.io/news/rss',                                type: 'rss', category: 'news' },

  // ─── GOOGLE NEWS (Real-time) ──────────────────────────────────────────────
  { name: 'Google News - AI',          url: 'https://news.google.com/rss/search?q=artificial+intelligence+AI&hl=en-US&gl=US&ceid=US:en',       type: 'rss', category: 'news' },
  { name: 'Google News - OpenAI',      url: 'https://news.google.com/rss/search?q=OpenAI+ChatGPT&hl=en-US&gl=US&ceid=US:en',                   type: 'rss', category: 'news' },
  { name: 'Google News - LLM',         url: 'https://news.google.com/rss/search?q=LLM+large+language+model&hl=en-US&gl=US&ceid=US:en',         type: 'rss', category: 'news' },
  { name: 'Google News - AI Funding',  url: 'https://news.google.com/rss/search?q=AI+startup+funding+investment&hl=en-US&gl=US&ceid=US:en',    type: 'rss', category: 'news' },
  { name: 'Google News - Gemini',      url: 'https://news.google.com/rss/search?q=Google+Gemini+AI&hl=en-US&gl=US&ceid=US:en',                 type: 'rss', category: 'news' },
  { name: 'Google News - Claude',      url: 'https://news.google.com/rss/search?q=Anthropic+Claude+AI&hl=en-US&gl=US&ceid=US:en',              type: 'rss', category: 'news' },
  { name: 'Google News - Grok',        url: 'https://news.google.com/rss/search?q=xAI+Grok+Elon+Musk&hl=en-US&gl=US&ceid=US:en',              type: 'rss', category: 'news' },
  { name: 'Google News - AI Models',   url: 'https://news.google.com/rss/search?q=AI+model+release+launch&hl=en-US&gl=US&ceid=US:en',          type: 'rss', category: 'news' },
  { name: 'Google News - Sam Altman',  url: 'https://news.google.com/rss/search?q=Sam+Altman&hl=en-US&gl=US&ceid=US:en',                       type: 'rss', category: 'news' },
  { name: 'Google News - Karpathy',    url: 'https://news.google.com/rss/search?q=Andrej+Karpathy&hl=en-US&gl=US&ceid=US:en',                  type: 'rss', category: 'news' },
  { name: 'Google News - LeCun',       url: 'https://news.google.com/rss/search?q=Yann+LeCun+Meta+AI&hl=en-US&gl=US&ceid=US:en',              type: 'rss', category: 'news' },
  { name: 'Google News - Jensen Huang',url: 'https://news.google.com/rss/search?q=Jensen+Huang+NVIDIA&hl=en-US&gl=US&ceid=US:en',              type: 'rss', category: 'news' },
  { name: 'Google News - Andrew Ng',   url: 'https://news.google.com/rss/search?q=Andrew+Ng+AI&hl=en-US&gl=US&ceid=US:en',                     type: 'rss', category: 'news' },
  { name: 'Google News - AI India',         url: 'https://news.google.com/rss/search?q=artificial+intelligence+India&hl=en-IN&gl=IN&ceid=IN:en',                           type: 'rss', category: 'news' },
  { name: 'Bing News - AI',                 url: 'https://www.bing.com/news/search?q=artificial+intelligence+AI&format=rss',                                                   type: 'rss', category: 'news' },
  { name: 'Bing News - LLM',               url: 'https://www.bing.com/news/search?q=LLM+GPT+Claude+Gemini&format=rss',                                                        type: 'rss', category: 'news' },

  // ─── LLM-SPECIFIC GOOGLE NEWS FEEDS ──────────────────────────────────────────
  { name: 'Google News - Anthropic Claude', url: 'https://news.google.com/rss/search?q=Anthropic+Claude+AI+model&hl=en-US&gl=US&ceid=US:en',                                  type: 'rss', category: 'news', company: 'Anthropic' },
  { name: 'Google News - Meta Llama',       url: 'https://news.google.com/rss/search?q=Meta+AI+Llama+model&hl=en-US&gl=US&ceid=US:en',                                        type: 'rss', category: 'news', company: 'Meta' },
  { name: 'Google News - Mistral AI',       url: 'https://news.google.com/rss/search?q=Mistral+AI+model+LLM&hl=en-US&gl=US&ceid=US:en',                                       type: 'rss', category: 'news', company: 'Mistral AI' },
  { name: 'Google News - DeepSeek',         url: 'https://news.google.com/rss/search?q=DeepSeek+AI+model&hl=en-US&gl=US&ceid=US:en',                                          type: 'rss', category: 'news', company: 'DeepSeek' },
  { name: 'Google News - xAI Grok',         url: 'https://news.google.com/rss/search?q=xAI+Grok+AI+model&hl=en-US&gl=US&ceid=US:en',                                         type: 'rss', category: 'news', company: 'xAI' },
  { name: 'Google News - HuggingFace',      url: 'https://news.google.com/rss/search?q=HuggingFace+open+source+AI&hl=en-US&gl=US&ceid=US:en',                                 type: 'rss', category: 'news', company: 'HuggingFace' },
  { name: 'Google News - NVIDIA AI',        url: 'https://news.google.com/rss/search?q=NVIDIA+AI+GPU+model&hl=en-US&gl=US&ceid=US:en',                                        type: 'rss', category: 'news', company: 'NVIDIA' },
  { name: 'Google News - Microsoft Copilot',url: 'https://news.google.com/rss/search?q=Microsoft+Copilot+AI+Azure&hl=en-US&gl=US&ceid=US:en',                                 type: 'rss', category: 'news', company: 'Microsoft' },
  { name: 'Google News - Google Gemini',    url: 'https://news.google.com/rss/search?q=Google+Gemini+2+AI+model&hl=en-US&gl=US&ceid=US:en',                                   type: 'rss', category: 'news', company: 'Google' },
  { name: 'Google News - Open Source LLM',  url: 'https://news.google.com/rss/search?q=open+source+LLM+AI+model+release&hl=en-US&gl=US&ceid=US:en',                          type: 'rss', category: 'news' },
  { name: 'Google News - AI Agents',        url: 'https://news.google.com/rss/search?q=AI+agent+autonomous+agentic&hl=en-US&gl=US&ceid=US:en',                                type: 'rss', category: 'news' },
  { name: 'Google News - AI New Features',  url: 'https://news.google.com/rss/search?q=AI+new+feature+launch+release+2025&hl=en-US&gl=US&ceid=US:en',                         type: 'rss', category: 'news' },

  // ─── INDUSTRY-SPECIFIC AI NEWS ────────────────────────────────────────────────
  { name: 'Google News - AI Healthcare',    url: 'https://news.google.com/rss/search?q=AI+healthcare+medical+clinical&hl=en-US&gl=US&ceid=US:en',                             type: 'rss', category: 'news' },
  { name: 'Google News - AI Finance',       url: 'https://news.google.com/rss/search?q=AI+finance+fintech+banking+trading&hl=en-US&gl=US&ceid=US:en',                         type: 'rss', category: 'news' },
  { name: 'Google News - AI Robotics',      url: 'https://news.google.com/rss/search?q=AI+robotics+autonomous+humanoid&hl=en-US&gl=US&ceid=US:en',                            type: 'rss', category: 'news' },
  { name: 'Google News - AI Legal',         url: 'https://news.google.com/rss/search?q=AI+legal+law+regulation+compliance&hl=en-US&gl=US&ceid=US:en',                         type: 'rss', category: 'news' },
  { name: 'Google News - AI Education',     url: 'https://news.google.com/rss/search?q=AI+education+learning+edtech&hl=en-US&gl=US&ceid=US:en',                               type: 'rss', category: 'news' },
  { name: 'Google News - AI Cybersecurity', url: 'https://news.google.com/rss/search?q=AI+cybersecurity+security+threat&hl=en-US&gl=US&ceid=US:en',                           type: 'rss', category: 'news' },
  { name: 'Google News - AI Chips',         url: 'https://news.google.com/rss/search?q=AI+chip+semiconductor+GPU+TPU&hl=en-US&gl=US&ceid=US:en',                              type: 'rss', category: 'news' },
  { name: 'Google News - Generative AI',    url: 'https://news.google.com/rss/search?q=generative+AI+image+video+audio&hl=en-US&gl=US&ceid=US:en',                            type: 'rss', category: 'news' },
  { name: 'Google News - AI Enterprise',    url: 'https://news.google.com/rss/search?q=enterprise+AI+automation+workflow&hl=en-US&gl=US&ceid=US:en',                          type: 'rss', category: 'news' },

  // ─── RESEARCH ─────────────────────────────────────────────────────────────
  { name: 'Arxiv CS.AI',          url: 'https://arxiv.org/rss/cs.AI',                                    type: 'rss', category: 'research' },
  { name: 'Arxiv CS.LG',          url: 'https://arxiv.org/rss/cs.LG',                                    type: 'rss', category: 'research' },
  { name: 'Arxiv CS.CL',          url: 'https://arxiv.org/rss/cs.CL',                                    type: 'rss', category: 'research' },
  { name: 'Papers With Code',      url: 'https://paperswithcode.com/rss.xml',                             type: 'rss', category: 'research' },
  { name: 'Google Research Blog',  url: 'https://research.google/blog/rss/',                              type: 'rss', category: 'research' },
  { name: 'Microsoft Research',    url: 'https://www.microsoft.com/en-us/research/blog/feed/',            type: 'rss', category: 'research' },
  { name: 'BAIR Blog',             url: 'https://bair.berkeley.edu/blog/feed.xml',                        type: 'rss', category: 'research' },
  { name: 'MIT AI News',           url: 'https://news.mit.edu/rss/topic/artificial-intelligence2',        type: 'rss', category: 'research' },
  { name: 'Stanford HAI',          url: 'https://hai.stanford.edu/news/rss.xml',                          type: 'rss', category: 'research' },
  { name: 'DeepMind Research',     url: 'https://deepmind.google/research/publications/rss.xml',          type: 'rss', category: 'research' },

  // ─── STARTUP & FUNDING ────────────────────────────────────────────────────
  { name: 'Crunchbase News',  url: 'https://news.crunchbase.com/feed/',        type: 'rss', category: 'news' },
  { name: 'Y Combinator Blog',url: 'https://www.ycombinator.com/blog/rss',    type: 'rss', category: 'news' },
  { name: 'a16z News',        url: 'https://a16z.com/feed/',                  type: 'rss', category: 'news' },
  { name: 'Tech.eu',          url: 'https://tech.eu/feed/',                   type: 'rss', category: 'news' },
  { name: 'Sifted',           url: 'https://sifted.eu/feed/',                 type: 'rss', category: 'news' },
  { name: 'Google News - AI Startup', url: 'https://news.google.com/rss/search?q=AI+startup+funding+series+round&hl=en-US&gl=US&ceid=US:en', type: 'rss', category: 'news' },

  // ─── DEVELOPER SOURCES ────────────────────────────────────────────────────
  { name: 'PyTorch Blog',     url: 'https://pytorch.org/blog/feed.xml',          type: 'rss', category: 'news' },
  { name: 'TensorFlow Blog',  url: 'https://blog.tensorflow.org/feeds/posts/default', type: 'rss', category: 'news' },
  { name: 'LangChain Blog',   url: 'https://blog.langchain.dev/rss/',             type: 'rss', category: 'news' },
  { name: 'LlamaIndex Blog',  url: 'https://www.llamaindex.ai/blog/rss.xml',     type: 'rss', category: 'news' },
  { name: 'Ollama Blog',      url: 'https://ollama.com/blog/rss',                type: 'rss', category: 'news' },
  { name: 'vLLM Blog',        url: 'https://blog.vllm.ai/feed.xml',              type: 'rss', category: 'news' },
  { name: 'Modal Blog',       url: 'https://modal.com/blog/rss',                 type: 'rss', category: 'news' },
  { name: 'Replicate Blog',   url: 'https://replicate.com/blog/rss',             type: 'rss', category: 'news' },
  { name: 'Vercel AI Blog',   url: 'https://vercel.com/blog/rss.xml',            type: 'rss', category: 'news' },
  { name: 'Cloudflare AI',    url: 'https://blog.cloudflare.com/tag/ai/rss/',    type: 'rss', category: 'news' },
  { name: 'OpenRouter News',  url: 'https://openrouter.ai/news/rss',             type: 'rss', category: 'news' },

  // ─── COMMUNITY ────────────────────────────────────────────────────────────
  { name: 'Hacker News AI',        url: 'https://hnrss.org/newest?q=AI+LLM+ChatGPT+Claude+Gemini',   type: 'rss', category: 'social' },
  { name: 'Hacker News Front',     url: 'https://hnrss.org/frontpage',                                type: 'rss', category: 'social' },
  { name: 'Reddit r/MachineLearning', url: 'https://www.reddit.com/r/MachineLearning/.rss',           type: 'rss', category: 'social' },
  { name: 'Reddit r/artificial',   url: 'https://www.reddit.com/r/artificial/.rss',                   type: 'rss', category: 'social' },
  { name: 'Reddit r/LocalLLaMA',   url: 'https://www.reddit.com/r/LocalLLaMA/.rss',                   type: 'rss', category: 'social' },
  { name: 'Reddit r/OpenAI',       url: 'https://www.reddit.com/r/OpenAI/.rss',                       type: 'rss', category: 'social' },
  { name: 'Reddit r/singularity',  url: 'https://www.reddit.com/r/singularity/.rss',                  type: 'rss', category: 'social' },
  { name: 'Product Hunt AI',       url: 'https://www.producthunt.com/feed?category=artificial-intelligence', type: 'rss', category: 'social' },
];

// High-priority GitHub repos to monitor for releases
export const GITHUB_REPOS = [
  'openai/openai-python',
  'anthropics/anthropic-sdk-python',
  'google/generative-ai-python',
  'huggingface/transformers',
  'langchain-ai/langchain',
  'microsoft/autogen',
  'run-llama/llama_index',
  'ollama/ollama',
  'ggerganov/llama.cpp',
  'vllm-project/vllm',
  'BerriAI/litellm',
  'openai/whisper',
  'Stability-AI/stablediffusion',
  'AUTOMATIC1111/stable-diffusion-webui',
  'comfyanonymous/ComfyUI',
  'mistralai/mistral-src',
  'microsoft/phi-2',
  'google/gemma',
  'meta-llama/llama',
  'deepseek-ai/DeepSeek-V3',
  'QwenLM/Qwen',
  'unslothai/unsloth',
  'guidance-ai/guidance',
  'modal-labs/modal-client',
  'vercel/ai',
];

// AI company/person keywords for importance detection
export const AI_COMPANY_KEYWORDS = [
  'openai', 'anthropic', 'google deepmind', 'google ai', 'meta ai',
  'microsoft ai', 'nvidia', 'hugging face', 'mistral', 'cohere',
  'stability ai', 'perplexity', 'xai', 'grok', 'sam altman',
  'sundar pichai', 'demis hassabis', 'yann lecun', 'ilya sutskever',
  'andrej karpathy', 'jensen huang', 'andrew ng', 'dario amodei',
  'gpt', 'claude', 'gemini', 'llama', 'chatgpt', 'copilot',
  'sora', 'dall-e', 'midjourney', 'runway', 'replicate',
  'groq', 'cerebras', 'elevenlabs', 'character ai', 'perplexity',
  'deepseek', 'qwen', 'mistral', 'phi', 'gemma',
  'langchain', 'llamaindex', 'ollama', 'vllm', 'rag',
  'agent', 'multi-agent', 'reasoning model', 'o1', 'o3',
];

// Founder/leader names for Google News tracking (already added as Google News RSS above)
export const AI_LEADERS = [
  'Sam Altman', 'Andrej Karpathy', 'Yann LeCun', 'Andrew Ng',
  'Demis Hassabis', 'Dario Amodei', 'Jensen Huang', 'Ilya Sutskever',
  'Greg Brockman', 'Emad Mostaque', 'Thomas Wolf', 'Aravind Srinivas',
  'Harrison Chase', 'Jerry Liu',
];
