export const FAQS = [
  { q: 'How long does custom software development take?',  a: 'Timelines depend entirely on scope. A focused internal tool typically takes 6 to 10 weeks. A full enterprise platform with multiple modules can take 4 to 8 months. After a discovery session, we give you a detailed milestone plan with fixed deadlines, not vague estimates.' },
  { q: 'What tech stack do you use?',                      a: 'We\'re stack-agnostic and choose based on your needs. Common choices: Next.js / React for frontend, Node.js or Python for backend, PostgreSQL / MongoDB for data, and AWS or GCP for infrastructure. We can also work within your existing stack.' },
  { q: 'Do you sign NDAs and handle IP ownership?',        a: 'Yes, NDA signing is standard before any discovery conversation. All IP, source code, and documentation built for your project transfers 100% to you upon final payment.' },
  { q: 'What happens after the software launches?',        a: 'We offer SLA-backed post-launch support packages covering monitoring, bug fixes, security patches, and feature development. You\'ll also receive complete documentation and handover so you\'re never locked in.' },
  { q: 'Can you integrate with our existing systems?',     a: 'API and system integration is a core capability. We regularly connect to ERPs, CRMs, payment gateways, third-party SaaS tools, and legacy databases. If it has an API (or even a database we can query), we can integrate it.' },
  { q: 'Do you build custom software for small businesses, or only large enterprises?', a: 'Both. We build custom software for small businesses that have outgrown spreadsheets and generic tools, as well as multi-module custom enterprise software for larger organizations. Scope and budget scale with your business, not the other way around.' },
  { q: 'What is the real difference between custom software and off-the-shelf tools?', a: 'Off-the-shelf software fits the average company, which means you bend your workflow to match the tool. Custom software is built around your exact process, data structure, and integrations, so it fits how your team already works instead of forcing a compromise.' },
  { q: 'When should a business build custom software instead of buying it?', a: 'When your workflow no longer fits off-the-shelf tools, when you are stitching together multiple SaaS subscriptions with manual workarounds, or when licensing costs for enterprise software scale faster than your team does. At that point, custom software usually pays for itself.' },
  { q: 'How do I know if I need custom software?', a: 'Signs include manual data re-entry between disconnected tools, workflows that require constant workarounds, or software licensing costs growing faster than your headcount. If your team is adapting to the tool instead of the tool adapting to you, it is worth a discovery conversation.' },
  { q: 'What does a custom software project typically cost?', a: 'A focused internal tool typically starts around $8,000 to $15,000. A full enterprise platform with multiple modules, integrations, and complex logic can run $40,000 and up. We give you a fixed quote after discovery based on actual scope, not a generic estimate.' },
]
