export const CATS = ['All', 'Website', 'Social Media', 'Branding']

export interface SocialHandle {
  platform: string
  url: string
  icon: string
  color: string
}

export interface SocialPost {
  type: 'post' | 'reel'
  image: string
  video?: string
  caption: string
  likes?: string
  views?: string
  postUrl?: string
}

export type ProjectTheme =
  | 'noir-editorial'
  | 'mac-window'
  | 'oversized-type'
  | 'gallery-grid'
  | 'stats-editorial'
  | 'video-case-study'

export interface Project {
  id: string
  cat: string[]
  theme?: ProjectTheme
  title: string
  industry: string
  industryIcon: string
  tagline: string
  desc: string
  contribution?: string
  services: string[]
  tech?: string[]
  colors?: { hex: string; name: string }[]
  animations?: string[]
  metrics?: { val: string; key: string }[]
  liveUrl?: string
  socialHandles?: SocialHandle[]
  socialPosts?: SocialPost[]
  logo?: string
  screenshot?: string
  screenshotFit?: 'cover' | 'contain'
  comingSoon?: boolean
  coverGradient: string
  coverIcon: string
}

export const projects: Project[] = [
  {
    id: 'laghima-jewelry',
    theme: 'noir-editorial',
    cat: ['Website', 'Social Media', 'Branding'],
    title: 'Laghima Jewelry',
    industry: 'Jewelry & Accessories',
    industryIcon: 'fa-gem',
    tagline: 'Premium gold and silver rings and bracelets, from brand identity to full digital presence.',
    desc: 'Complete brand presence built for Laghima Jewelry, a luxury jewelry brand specializing in handcrafted gold and silver rings and bracelets. We developed the full brand identity including logo, typography, and color palette, then designed and built an elegant catalog website, and grew their Instagram presence with premium curated content.',
    contribution: 'We built Laghima Jewelry from the ground up: the brand identity (logo, typography, gold-and-onyx color system), a full e-commerce catalog website with category browsing and wishlist, and an Instagram content and growth strategy that took their following from zero to an engaged premium audience.',
    services: [
      'Brand Identity & Logo Design',
      'Website Design & Development',
      'Social Media Management',
      'Content Creation & Photography Direction',
      'Instagram Growth Strategy',
    ],
    tech: ['Next.js', 'Tailwind CSS', 'Figma'],
    colors: [
      { hex: '#C9A84C', name: 'Gold' },
      { hex: '#1A1A1A', name: 'Onyx' },
      { hex: '#F5F0E8', name: 'Ivory' },
      { hex: '#8B6914', name: 'Burnished Gold' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    animations: [
      'Fade-in on scroll for all product sections',
      'Hover zoom on jewelry product cards',
      'Gold shimmer text effect on brand name',
      'Smooth page transition animations',
    ],
    metrics: [
      { val: '3x', key: 'Instagram Growth' },
      { val: '5K+', key: 'Followers' },
      { val: '40%', key: 'Engagement Rate' },
    ],
    liveUrl: '#',
    socialHandles: [],
    logo: '/assets/img/logos/laghima_logo.jpeg',
    screenshot: '/assets/img/projects images/optimized/laghima-jewelry.webp',
    socialPosts: [
      { type: 'post', image: '/assets/img/social media posts/post/optimized/laghima-ring.webp', caption: 'Handcrafted gold ring, product detail shot' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/laghima-pendant.webp', caption: 'Pendant showcase' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/laghima-special-collection.webp', caption: 'Special collection launch' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/laghima-box-opening.webp', video: '/assets/img/social media posts/video/optimized/laghima-box-opening.mp4', caption: 'Unboxing experience reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/laghima-jewellery.webp', video: '/assets/img/social media posts/video/optimized/laghima-jewellery.mp4', caption: 'Jewellery showcase reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/laghima-ring-design.webp', video: '/assets/img/social media posts/video/optimized/laghima-ring-design.mp4', caption: 'Ring design process reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/laghima-advertise-reel.webp', video: '/assets/img/social media posts/video/optimized/laghima-advertise-reel.mp4', caption: 'Brand campaign reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/laghima-ring-showcase.webp', video: '/assets/img/social media posts/video/optimized/laghima-ring-showcase.mp4', caption: 'Ring showcase reel' },
    ],
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #0d1435 50%, #1a237e 100%)',
    coverIcon: 'fa-gem',
  },
  {
    id: 'aklr-foundation',
    theme: 'stats-editorial',
    cat: ['Website', 'Social Media'],
    title: 'AKLR Foundation',
    industry: 'NGO & Event Services',
    industryIcon: 'fa-leaf',
    tagline: 'Nature conservation NGO and premium furniture rental for corporate events and weddings.',
    desc: 'AKLR Foundation operates on two fronts: environmental conservation work focused on air, water, and earth wellness, and a premium furniture rental service for corporate events, SPX setups, and weddings. We built a dual-purpose website that clearly presents both verticals and manages their growing social media community.',
    contribution: 'We designed and built a dual-purpose site that keeps AKLR Foundation\'s conservation mission and their events/furniture-rental business each clearly presented without confusing visitors, and we run their ongoing social media content and community management.',
    services: [
      'Website Design & Development',
      'Social Media Management',
      'Content Strategy & Creation',
      'Brand Positioning',
      'Event Inquiry System Integration',
    ],
    tech: ['WordPress', 'PHP', 'Figma', 'HTML/CSS'],
    colors: [
      { hex: '#2D5016', name: 'Forest Green' },
      { hex: '#6B8F3A', name: 'Leaf Green' },
      { hex: '#F4F1E8', name: 'Natural Cream' },
      { hex: '#8B7355', name: 'Earth Brown' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    animations: [
      'Nature-inspired parallax scroll',
      'Leaf floating particle effect',
      'Section fade-in on scroll',
      'Hover lift on service cards',
    ],
    metrics: [
      { val: '2K+', key: 'Social Followers' },
      { val: '85%', key: 'Web Inquiries' },
      { val: '12+', key: 'Events Supported' },
    ],
    liveUrl: 'https://aklrfoundation.com',
    socialHandles: [],
    logo: '/assets/img/logos/AKLR Foundation Logo.png',
    screenshot: '/assets/img/projects images/optimized/aklr-foundation.webp',
    socialPosts: [
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-foundation-environmental-concern.webp', video: '/assets/img/social media posts/video/optimized/aklr-foundation-environmental-concern.mp4', caption: 'Environmental concern awareness reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-foundation-healthier-tomorrow.webp', video: '/assets/img/social media posts/video/optimized/aklr-foundation-healthier-tomorrow.mp4', caption: 'Creating awareness for a healthier tomorrow' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-foundation-education-reel.webp', video: '/assets/img/social media posts/video/optimized/aklr-foundation-education-reel.mp4', caption: 'Conservation education reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-foundation-water-concern.webp', video: '/assets/img/social media posts/video/optimized/aklr-foundation-water-concern.mp4', caption: 'Water conservation awareness reel' },
    ],
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #071c28 50%, #005f6b 100%)',
    coverIcon: 'fa-leaf',
  },
  {
    id: 'blessings-foundation',
    theme: 'mac-window',
    cat: ['Website'],
    title: 'Blessings Foundation',
    industry: 'Healthcare & Wellness',
    industryIcon: 'fa-user-doctor',
    tagline: 'Clean, trust-building static website for a doctor-led healthcare initiative.',
    desc: 'Designed and developed a professional static website for Blessings Foundation, a doctor-led healthcare and wellness initiative based in Gurgaon. The site presents the doctor\'s credentials, specializations, consultation process, and contact details with a calm, trustworthy aesthetic that patients immediately connect with.',
    contribution: 'We designed and built the full static site for Blessings Foundation, including the service pages, credentials presentation, and on-page SEO setup, focused on giving patients a fast, trustworthy first impression.',
    services: [
      'Website Design',
      'Static Website Development',
      'On-page SEO Setup',
      'Content Writing',
    ],
    tech: ['HTML/CSS', 'JavaScript', 'Figma'],
    colors: [
      { hex: '#1565C0', name: 'Medical Blue' },
      { hex: '#FFFFFF', name: 'White' },
      { hex: '#E3F2FD', name: 'Sky Blue' },
      { hex: '#0D47A1', name: 'Deep Blue' },
      { hex: '#F5F5F5', name: 'Light Grey' },
    ],
    animations: [
      'Smooth scroll behavior',
      'Counter animations on stat numbers',
      'Fade-in on section scroll',
      'Subtle button hover effects',
    ],
    metrics: [
      { val: '<1s', key: 'Page Load Time' },
      { val: 'A+', key: 'Performance Score' },
      { val: '100%', key: 'Mobile Responsive' },
    ],
    liveUrl: 'https://blessingsfoundation.in',
    socialHandles: [],
    logo: '/assets/img/logos/blessing foundation logo.png',
    screenshot: '/assets/img/projects images/optimized/blessings-foundation.webp',
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #0d2040 50%, #0d47a1 100%)',
    coverIcon: 'fa-user-doctor',
  },
  {
    id: 'thinkvirtual',
    theme: 'gallery-grid',
    cat: ['Website', 'Social Media'],
    title: 'ThinkVirtual',
    industry: 'Technology & Digital',
    industryIcon: 'fa-vr-cardboard',
    tagline: 'Social media identity and community built from scratch for a digital-first brand.',
    desc: 'Built and managed the complete social media presence for ThinkVirtual, setting up the account identity, defining a consistent brand voice, creating a content calendar, and growing an engaged audience through creative, platform-optimized content.',
    contribution: 'We set up ThinkVirtual\'s social accounts from zero, defined its brand voice, and have run the ongoing content calendar and community management that grew it to an engaged, active following.',
    services: [
      'Social Media Account Setup',
      'Brand Voice & Tone Definition',
      'Content Creation',
      'Content Calendar Management',
      'Community Management',
    ],
    colors: [
      { hex: '#7C3AED', name: 'Electric Violet' },
      { hex: '#1E1B4B', name: 'Deep Indigo' },
      { hex: '#A78BFA', name: 'Lavender' },
      { hex: '#4C1D95', name: 'Dark Violet' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    metrics: [
      { val: '3.5K+', key: 'Followers' },
      { val: '6.8%', key: 'Engagement Rate' },
      { val: '60+', key: 'Posts Created' },
    ],
    liveUrl: 'https://thinkvirtual.in',
    socialHandles: [],
    logo: '/assets/img/logos/thinkvirtual logo.png',
    screenshot: '/assets/img/projects images/optimized/thinkvirtual.webp',
    socialPosts: [
      { type: 'post', image: '/assets/img/social media posts/post/optimized/thinkvirtual-share-learning.webp', caption: 'Share your biggest learning this week' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/thinkvirtual-campaign-vs-post.webp', caption: 'One post ends in a day, a proper campaign builds something long-term' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/thinkvirtual-strategy-execution.webp', caption: 'Your real value shows when your strategy actually gets executed' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/thinkvirtual-hiring-myths.webp', caption: 'Myths vs facts: the smart way to hire' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/thinkvirtual-right-people.webp', caption: 'The right people, the right time, the right impact' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/thinkvirtual-flexible-solutions.webp', caption: 'You don\'t always need a team, you need the right people at the right time' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/thinkvirtual-introduction.webp', video: '/assets/img/social media posts/video/optimized/thinkvirtual-introduction.mp4', caption: 'ThinkVirtual introduction reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/thinkvirtual-daily-problems.webp', video: '/assets/img/social media posts/video/optimized/thinkvirtual-daily-problems.mp4', caption: 'Daily problems, solved reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/thinkvirtual-indian-problems.webp', video: '/assets/img/social media posts/video/optimized/thinkvirtual-indian-problems.mp4', caption: 'Indian workplace problems reel' },
    ],
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #0f0d2e 50%, #312e81 100%)',
    coverIcon: 'fa-vr-cardboard',
  },
  {
    id: 'wavcart',
    theme: 'oversized-type',
    cat: ['Website', 'Social Media'],
    title: 'WavCart',
    industry: 'E-Commerce',
    industryIcon: 'fa-cart-shopping',
    tagline: 'Website design and conversion-focused social media for a WhatsApp-commerce brand.',
    desc: 'Built the website and managed end-to-end social media for WavCart, a WhatsApp commerce and retail automation platform. Delivered the site design alongside platform setup, content strategy, creative production, and audience building, helping position WavCart as a trusted shopping platform through consistent, conversion-driven storytelling.',
    contribution: 'We designed and built WavCart\'s website and own its social media end-to-end: platform setup, content strategy, creative production, and audience growth, positioning it as a trusted local-shop WhatsApp ordering platform through consistent, conversion-focused storytelling.',
    services: [
      'Website Design & Development',
      'Social Media Management',
      'Content Creation & Design',
      'Meta Ads Strategy',
      'Reels & Video Production',
      'Audience Growth',
    ],
    colors: [
      { hex: '#00BCD4', name: 'Cyan' },
      { hex: '#0A1628', name: 'Deep Navy' },
      { hex: '#E0F7FA', name: 'Light Cyan' },
      { hex: '#006064', name: 'Teal Dark' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    metrics: [
      { val: '8K+', key: 'Followers Gained' },
      { val: '4.2%', key: 'Engagement Rate' },
      { val: '2x', key: 'Reach Growth' },
    ],
    liveUrl: '#',
    socialHandles: [],
    logo: '/assets/img/logos/wavcart logo.png',
    screenshot: '/assets/img/projects images/optimized/wavcart.webp',
    screenshotFit: 'contain',
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #071e28 50%, #006e7f 100%)',
    coverIcon: 'fa-cart-shopping',
  },
  {
    id: 'rewa-education',
    theme: 'video-case-study',
    cat: ['Social Media'],
    title: 'Rewa Education',
    industry: 'K-5 Education',
    industryIcon: 'fa-book-open',
    tagline: 'Warm social media for a kids learning centre covering Grades 1-5 academics and moral values.',
    desc: 'Created and managed the social media presence for Rewa Education, a learning centre providing academic classes for children from Grades 1 to 5, combined with a strong focus on moral values and character development. Content is warm, colorful, and parent-focused to build trust and grow community.',
    contribution: 'We set up and manage Rewa Education\'s social accounts, producing warm, parent-focused content that builds trust in the centre\'s academic and values-based teaching approach.',
    services: [
      'Social Media Handle Setup',
      'Content Creation for Parents and Kids',
      'Educational Content Strategy',
      'Parent Community Building',
    ],
    colors: [
      { hex: '#F59E0B', name: 'Sunshine Yellow' },
      { hex: '#FEF3C7', name: 'Light Yellow' },
      { hex: '#D97706', name: 'Amber' },
      { hex: '#1A1A1A', name: 'Dark' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    metrics: [
      { val: '1.2K+', key: 'Followers' },
      { val: '7%', key: 'Engagement Rate' },
      { val: '45+', key: 'Posts Published' },
    ],
    socialHandles: [],
    logo: '/assets/img/logos/rewa education logo.png',
    socialPosts: [
      { type: 'post', image: '/assets/img/social media posts/post/optimized/rewa-education-blooms.webp', caption: 'Every Child Blooms in Their Own Time' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/rewa-education-dream-classroom.webp', caption: 'Every dream starts in a classroom' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/rewa-education-confidence.webp', caption: 'Confidence Starts With Speaking Up' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/rewa-education-science-4.webp', caption: 'Hands-on science learning' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/rewa-education-big-discoveries.webp', caption: 'Big discoveries start small' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/rewa-education-chocolate-day.webp', video: '/assets/img/social media posts/video/optimized/rewa-education-chocolate-day.mp4', caption: 'Chocolate Day classroom fun' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/rewa-education-summer-learning.webp', video: '/assets/img/social media posts/video/optimized/rewa-education-summer-learning.mp4', caption: 'REWA Summer Learning Program' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/rewa-education-guess-the-mistake.webp', video: '/assets/img/social media posts/video/optimized/rewa-education-guess-the-mistake.mp4', caption: 'Guess the Mistake challenge' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/rewa-education-guess-colour-challenge.webp', video: '/assets/img/social media posts/video/optimized/rewa-education-guess-colour-challenge.mp4', caption: 'Guess the Colour challenge' },
    ],
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #0d1435 50%, #1565c0 100%)',
    coverIcon: 'fa-book-open',
  },
  {
    id: 'aklr-academy',
    theme: 'gallery-grid',
    cat: ['Website', 'Social Media'],
    title: 'AKLR Academy',
    industry: 'AI Education & Online Courses',
    industryIcon: 'fa-robot',
    tagline: 'Social media for an AI-focused online education platform offering courses and live classes.',
    desc: 'Built and managed the social media identity for AKLR Academy, an online education platform specializing in AI learning through structured courses and live classes. Content focuses on making AI accessible to beginners, showcasing learning outcomes, and building a community of motivated learners.',
    contribution: 'We built AKLR Academy\'s social identity and run its content strategy, focused on making AI learning approachable for beginners and showcasing real learner outcomes to build a motivated community.',
    services: [
      'Social Media Handle Setup',
      'AI Education Content Creation',
      'Course Promotion Strategy',
      'Community Building',
    ],
    colors: [
      { hex: '#4F46E5', name: 'Indigo' },
      { hex: '#0F0C29', name: 'Deep Dark' },
      { hex: '#818CF8', name: 'Soft Indigo' },
      { hex: '#312E81', name: 'Dark Indigo' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    metrics: [
      { val: '2K+', key: 'Followers' },
      { val: '5.5%', key: 'Engagement Rate' },
      { val: '80+', key: 'Educational Posts' },
    ],
    liveUrl: 'https://aklracademy.com',
    socialHandles: [],
    logo: '/assets/img/logos/aklr academy logo.png',
    screenshot: '/assets/img/projects images/optimized/aklr-academy.webp',
    socialPosts: [
      { type: 'post', image: '/assets/img/social media posts/post/optimized/aklr-academy-professional-learning.webp', caption: 'AI for Professional Learning course' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/aklr-academy-invisible-ai-challenge.webp', caption: 'The Invisible AI Challenge: count how many AI tools you already use' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/aklr-academy-ai-iceberg.webp', caption: 'What AI actually is: automation, agents, RAG, coding and more beneath the surface' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/aklr-academy-ai-hallucination.webp', caption: 'AI can lie: understanding AI hallucination' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/aklr-academy-billboard.webp', caption: 'AKLR Academy billboard: AI skills today, better future' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-academy-ai-learning.webp', video: '/assets/img/social media posts/video/optimized/aklr-academy-ai-learning.mp4', caption: 'Future-Ready AI Learning' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-academy-programs.webp', video: '/assets/img/social media posts/video/optimized/aklr-academy-programs.mp4', caption: 'Course programs overview' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-academy-ai-learning-2.webp', video: '/assets/img/social media posts/video/optimized/aklr-academy-ai-learning-2.mp4', caption: 'AI learning in action' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-academy-world-youth-skills-day.webp', video: '/assets/img/social media posts/video/optimized/aklr-academy-world-youth-skills-day.mp4', caption: 'World Youth Skills Day: the skills that won\'t expire' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-academy-ai-puzzle.webp', video: '/assets/img/social media posts/video/optimized/aklr-academy-ai-puzzle.mp4', caption: 'AI is a puzzle: every piece unlocks a new skill' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-academy-why-ai-story.webp', video: '/assets/img/social media posts/video/optimized/aklr-academy-why-ai-story.mp4', caption: 'Why AI: a brand story on making AI education accessible to every family' },
    ],
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #0f0d2e 50%, #283593 100%)',
    coverIcon: 'fa-robot',
  },
  {
    id: 'aklr-tech',
    theme: 'gallery-grid',
    cat: ['Website', 'Social Media'],
    title: 'AKLR Tech',
    industry: 'IT Services & Technology',
    industryIcon: 'fa-microchip',
    tagline: 'Professional social media for an IT services and technology news brand.',
    desc: 'Managed the social media presence for AKLR Tech, an IT services company that also covers technology news and industry updates. We developed a professional, authoritative content strategy covering tech news, service highlights, and insights to establish credibility and attract business clients.',
    contribution: 'We manage AKLR Tech\'s social presence with a professional, authoritative content strategy mixing tech news, service highlights, and insights, built to attract and convert business clients.',
    services: [
      'Social Media Management',
      'Tech News Content Curation',
      'Service Highlight Campaigns',
      'Brand Positioning',
      'Audience Growth',
    ],
    colors: [
      { hex: '#00BCD4', name: 'Tech Cyan' },
      { hex: '#0D1117', name: 'Code Black' },
      { hex: '#00E5FF', name: 'Electric Blue' },
      { hex: '#006064', name: 'Dark Teal' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    metrics: [
      { val: '1.8K+', key: 'Followers' },
      { val: '4.8%', key: 'Engagement Rate' },
      { val: '100+', key: 'Posts Published' },
    ],
    liveUrl: 'https://aklrtech.com',
    socialHandles: [],
    logo: '/assets/img/logos/AKLR Tech logo.png',
    screenshot: '/assets/img/projects images/optimized/aklr-tech.webp',
    socialPosts: [
      { type: 'post', image: '/assets/img/social media posts/post/optimized/aklr-tech-ai-future-of-space.webp', caption: 'AI powering the future of space' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/aklr-tech-ai-innovations-concept.webp', caption: 'AI innovations not in the market yet' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/aklr-tech-ai-and-you.webp', caption: 'The future is here: AI & you' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/aklr-tech-ai-workflow.webp', caption: 'An AI workflow that saves 4 hours every day' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/aklr-tech-ai-2030.webp', caption: 'AI in 2030: what will daily life look like?' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-tech-biggest-mistakes.webp', video: '/assets/img/social media posts/video/optimized/aklr-tech-biggest-mistakes.mp4', caption: 'The biggest AI mistakes to avoid' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-tech-ai-tools-reel.webp', video: '/assets/img/social media posts/video/optimized/aklr-tech-ai-tools-reel.mp4', caption: 'AI tools walkthrough reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/aklr-tech-discussion-reel.webp', video: '/assets/img/social media posts/video/optimized/aklr-tech-discussion-reel.mp4', caption: 'AI discussion reel' },
    ],
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #071828 50%, #01579b 100%)',
    coverIcon: 'fa-microchip',
  },
  {
    id: 'vibestyl',
    theme: 'oversized-type',
    cat: ['Website', 'Social Media', 'Branding'],
    title: 'VibéStyl',
    industry: 'Fashion & Clothing',
    industryIcon: 'fa-shirt',
    tagline: 'Trendy clothing store with a full e-commerce website. Browse, pick, and order online.',
    desc: 'Designed and developed a full e-commerce website for VibéStyl, a fashion-forward clothing brand. The site features a product catalog with category filters, size and color selection, a smooth cart experience, and a clean checkout flow. The brand identity was built to match the vibe: bold, modern, and unapologetically stylish.',
    contribution: 'We built VibéStyl\'s full e-commerce experience and brand identity from scratch, including the product catalog, cart and checkout flow, and an AI-powered virtual try-on feature that sets it apart from typical fashion storefronts.',
    services: [
      'E-commerce Website Design & Development',
      'Brand Identity & Logo',
      'Product Catalog Setup',
      'Mobile-first UI Design',
      'Checkout & Order Flow',
      'Social Media Content & Reels',
    ],
    tech: ['HTML/CSS', 'JavaScript', 'Figma'],
    colors: [
      { hex: '#131C25', name: 'Charcoal' },
      { hex: '#BC9C27', name: 'Gold' },
      { hex: '#F4F1E5', name: 'Cream' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    animations: [
      'Product image hover zoom',
      'Smooth cart slide-in drawer',
      'Color and size selector transitions',
      'Scroll-reveal on product grid',
    ],
    metrics: [
      { val: '100%', key: 'Mobile Responsive' },
      { val: '<1.2s', key: 'Page Load' },
      { val: '50+', key: 'Products Listed' },
    ],
    liveUrl: '#',
    socialHandles: [],
    logo: '/assets/img/logos/vibestyl logo.png',
    screenshot: '/assets/img/social media posts/video/posters/vibestyl-mobile-ui.webp',
    screenshotFit: 'contain',
    socialPosts: [
      { type: 'reel', image: '/assets/img/social media posts/video/posters/vibestyl-new-collections.webp', video: '/assets/img/social media posts/video/optimized/vibestyl-new-collections.mp4', caption: 'New collection reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/vibestyl-western-wear.webp', video: '/assets/img/social media posts/video/optimized/vibestyl-western-wear.mp4', caption: 'Western wear collection reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/vibestyl-nightwear-collections.webp', video: '/assets/img/social media posts/video/optimized/vibestyl-nightwear-collections.mp4', caption: 'Nightwear collection reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/vibestyl-fit-check.webp', video: '/assets/img/social media posts/video/optimized/vibestyl-fit-check.mp4', caption: 'Fit check reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/vibestyl-shopping-bag.webp', video: '/assets/img/social media posts/video/optimized/vibestyl-shopping-bag.mp4', caption: 'Shopping bag reveal reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/vibestyl-mobile-ui.webp', video: '/assets/img/social media posts/video/optimized/vibestyl-mobile-ui.mp4', caption: 'Mobile app UI showcase reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/vibestyl-stop-scrolling.webp', video: '/assets/img/social media posts/video/optimized/vibestyl-stop-scrolling.mp4', caption: 'Stop-scroll hook reel' },
    ],
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #0c1030 50%, #1a237e 100%)',
    coverIcon: 'fa-shirt',
  },
  {
    id: 'shrisurbhikripa',
    theme: 'mac-window',
    cat: ['Website', 'Social Media'],
    title: 'Shri Surbhi Kripa',
    industry: 'Organic & Natural Products',
    industryIcon: 'fa-seedling',
    tagline: 'Static product website for an organic goods brand. Browse the catalog and order via WhatsApp.',
    desc: 'Designed and built a clean static product showcase website for Shri Surbhi Kripa, a brand dealing in pure, natural A2 desi cow products, organic foods, and Ayurvedic essentials. Customers browse the full product catalog on the website and place orders directly through WhatsApp, making the buying process simple and personal. The design reflects the brand\'s natural, trustworthy character.',
    contribution: 'We designed and built the full catalog site for Shri Surbhi Kripa and set up its WhatsApp order flow, so "Add to Cart" sends the order straight into a WhatsApp chat instead of a traditional checkout, matching how the brand\'s customers actually prefer to buy.',
    services: [
      'Static Website Design & Development',
      'Product Catalog Design',
      'WhatsApp Order Integration',
      'SEO Setup',
      'Content Writing',
    ],
    tech: ['HTML/CSS', 'JavaScript', 'Figma'],
    colors: [
      { hex: '#1B5E20', name: 'Deep Green' },
      { hex: '#4CAF50', name: 'Leaf Green' },
      { hex: '#F1F8E9', name: 'Natural Cream' },
      { hex: '#8D6E63', name: 'Earthy Brown' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    animations: [
      'Fade-in on scroll for product cards',
      'Hover lift on product images',
      'WhatsApp button pulse effect',
      'Smooth scroll navigation',
    ],
    metrics: [
      { val: 'WhatsApp', key: 'Order Channel' },
      { val: '<1s', key: 'Page Load' },
      { val: '100%', key: 'Mobile Friendly' },
    ],
    liveUrl: 'https://shrisurbhikripa.com',
    socialHandles: [],
    logo: '/assets/img/logos/Shree_Shurbhi_Kirpa_logo.png',
    screenshot: '/assets/img/projects images/optimized/shrisurbhikripa.webp',
    socialPosts: [
      { type: 'post', image: '/assets/img/social media posts/post/optimized/shrisurbhikripa-amla-chavanprash.webp', caption: 'Amla Chavanprash product feature' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/shrisurbhikripa-chandan-ke-gunn.webp', caption: 'Benefits of Chandan (Sandalwood)' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/shrisurbhikripa-juice-comparison.webp', caption: 'Juice range comparison' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/shrisurbhikripa-trifala-churan.webp', caption: 'Trifala Churan product feature' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/shrisurbhikripa-candy-ad.webp', video: '/assets/img/social media posts/video/optimized/shrisurbhikripa-candy-ad.mp4', caption: 'Candy product ad reel' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/shrisurbhikripa-rudraksha-mala-reel.webp', video: '/assets/img/social media posts/video/optimized/shrisurbhikripa-rudraksha-mala-reel.mp4', caption: 'Rudraksha Mala showcase reel' },
    ],
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #071c30 50%, #00607a 100%)',
    coverIcon: 'fa-seedling',
  },
  {
    id: 'a2z-graphics',
    theme: 'mac-window',
    cat: ['Website'],
    title: 'A2Z Graphics & Computer',
    industry: 'Printing & Design Services',
    industryIcon: 'fa-print',
    tagline: 'Static showcase website for a full-service printing and graphic design studio.',
    desc: 'Designed and developed a static product and service showcase website for A2Z Graphics and Computer, a studio offering comprehensive printing and graphic design services since 2015. The site presents their service offerings, past work samples, and contact details in a bold, professional layout that mirrors their creative expertise, with inquiries routed through WhatsApp.',
    contribution: 'We designed and built A2Z Graphics\' full service and portfolio showcase site, including their WhatsApp-based inquiry setup, giving a 9-year-old print and design studio a digital presence that matches their creative quality.',
    services: [
      'Website Design & Development',
      'Service Portfolio Showcase',
      'Work Gallery Integration',
      'Contact & Inquiry Setup',
      'SEO Setup',
    ],
    tech: ['HTML/CSS', 'JavaScript', 'Figma'],
    colors: [
      { hex: '#E65100', name: 'Print Orange' },
      { hex: '#0D0D0D', name: 'Ink Black' },
      { hex: '#FFF3E0', name: 'Warm White' },
      { hex: '#BF360C', name: 'Deep Red' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    animations: [
      'Gallery image hover zoom',
      'Scroll-reveal on service cards',
      'Fade-in section transitions',
      'Smooth anchor link scroll',
    ],
    metrics: [
      { val: '500+', key: 'Happy Clients' },
      { val: '19+', key: 'Services Showcased' },
      { val: '2015', key: 'Since' },
    ],
    liveUrl: '#',
    socialHandles: [],
    screenshot: '/assets/img/projects images/optimized/a2z-graphics.webp',
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #0e0d30 50%, #4527a0 100%)',
    coverIcon: 'fa-print',
  },
  {
    id: 'amw-solar',
    theme: 'mac-window',
    cat: ['Website'],
    title: 'AMW Solar',
    industry: 'Renewable Energy & Solar Products',
    industryIcon: 'fa-solar-panel',
    tagline: 'Enquiry-driven catalog website for a solar flood-light seller. Get a quote, not a cart checkout.',
    desc: 'Designed and developed a product catalog website for AMW Solar, a business selling eco-friendly, cost-effective solar flood lights. Instead of a traditional e-commerce checkout, the site is built around a "Get Quote" enquiry flow suited to bulk and B2B solar-lighting purchases, presenting the product range with specs and letting buyers request pricing directly.',
    contribution: 'We built AMW Solar\'s full catalog site end-to-end, including the spec-sheet presentation for each flood-light model and a quote-request flow in place of a cart, matching how solar-lighting buyers actually purchase: bulk orders, price on request.',
    services: [
      'Website Design & Development',
      'Product Catalog Design',
      'Quote/Enquiry Flow Setup',
      'On-page SEO Setup',
      'Content Writing',
    ],
    tech: ['HTML/CSS', 'JavaScript', 'Figma'],
    colors: [
      { hex: '#0D47A1', name: 'Solar Blue' },
      { hex: '#1976D2', name: 'Bright Blue' },
      { hex: '#E3F2FD', name: 'Sky Blue' },
      { hex: '#FFC107', name: 'Solar Yellow' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    animations: [
      'Fade-in on scroll for product sections',
      'Hover lift on product cards',
      'Smooth anchor link scroll',
    ],
    metrics: [
      { val: '<1s', key: 'Page Load Time' },
      { val: '100%', key: 'Mobile Responsive' },
    ],
    liveUrl: 'https://amwsolar.com',
    socialHandles: [],
    screenshot: '/assets/img/projects images/optimized/amw-solar.webp',
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #0d2040 50%, #0d47a1 100%)',
    coverIcon: 'fa-solar-panel',
  },
  {
    id: 'mythinkai',
    theme: 'video-case-study',
    cat: ['Website', 'Social Media'],
    title: 'MyThinkAI',
    industry: 'AI Lead Generation',
    industryIcon: 'fa-bullseye',
    tagline: 'AI-powered lead generation tool that builds targeted contact lists by location, occupation, and category.',
    desc: 'MyThinkAI is a ThinkSuite product that generates qualified leads based on location, occupation, and other business categories, delivering ready-to-use, targeted contact lists for outreach. We are building both its website and its social media presence.',
    contribution: 'We are building MyThinkAI\'s website and setting up and running its social media presence from day one, ahead of public launch.',
    services: [
      'Website Design & Development',
      'Social Media Account Setup',
      'Content Strategy & Creation',
      'Brand Positioning',
    ],
    tech: ['Next.js', 'Tailwind CSS'],
    colors: [
      { hex: '#4F46E5', name: 'Indigo' },
      { hex: '#0F0C29', name: 'Deep Dark' },
      { hex: '#818CF8', name: 'Soft Indigo' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    liveUrl: '#',
    socialHandles: [],
    logo: '/assets/img/logos/mythinkai logo.jpeg',
    screenshot: '/assets/img/projects images/optimized/mythinkai.webp',
    socialPosts: [
      { type: 'post', image: '/assets/img/social media posts/post/optimized/mythinkai-comparison.webp', caption: 'Side-by-side comparison + 3 advantages nobody tells you' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/mythinkai-competitor-analysis.webp', caption: '3 competitors analyzed: content gap + keyword gap, found in minutes' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/mythinkai-ai-tools.webp', caption: '3 AI tools, 3 styles, endless possibilities' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/mythinkai-google-business-posts.webp', caption: '10 Google Business posts: city + competitor, done' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/mythinkai-local-seo.webp', caption: 'Local keyword posts, ready to publish for local SEO' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/mythinkai-product-url.webp', caption: 'Drop a product URL, get ready-to-post copy for 6 platforms' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/mythinkai-lead-search.webp', caption: 'Find restaurant owners faster: 20 verified leads ready' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/mythinkai-maps-leads.webp', caption: '20 leads from Google Maps in 60 seconds, no payment' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/mythinkai-product-reel.webp', video: '/assets/img/social media posts/video/optimized/mythinkai-product-reel.mp4', caption: 'Product walkthrough reel' },
    ],
    comingSoon: true,
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #0f0d2e 50%, #312e81 100%)',
    coverIcon: 'fa-bullseye',
  },
  {
    id: 'visibility-ai',
    cat: ['Website'],
    title: 'Visibility AI',
    industry: 'AI Search Optimization (GEO)',
    industryIcon: 'fa-magnifying-glass-chart',
    tagline: 'AI tool that helps businesses get found and cited by AI search engines like ChatGPT and Perplexity.',
    desc: 'Visibility AI is a ThinkSuite product built to help businesses rank and get cited in AI-powered search and answer engines, not just traditional Google search. We are building its platform and website.',
    contribution: 'We are building Visibility AI\'s full website and platform from the ground up, ahead of public launch.',
    services: [
      'Website Design & Development',
      'Platform Build',
      'Brand Positioning',
    ],
    tech: ['Next.js', 'Tailwind CSS'],
    colors: [
      { hex: '#00BCD4', name: 'Cyan' },
      { hex: '#0A1628', name: 'Deep Navy' },
      { hex: '#E0F7FA', name: 'Light Cyan' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    liveUrl: '#',
    socialHandles: [],
    logo: '/assets/img/logos/visibility ai logo.png',
    screenshot: '/assets/img/projects images/optimized/visibility-ai.webp',
    comingSoon: true,
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #071e28 50%, #006e7f 100%)',
    coverIcon: 'fa-magnifying-glass-chart',
  },
  {
    id: 'for-events',
    theme: 'stats-editorial',
    cat: ['Social Media'],
    title: 'F.O.R Events',
    industry: 'Event Management & Services',
    industryIcon: 'fa-calendar-days',
    tagline: 'Professional event planning and management, brought to life through engaging social content.',
    desc: 'F.O.R Events is an event management and planning company. We run their social media presence, producing content that showcases their event execution and services to build credibility with prospective clients.',
    contribution: 'We manage F.O.R Events\' social media presence, producing reels and content that showcase their event planning and execution work.',
    services: [
      'Social Media Management',
      'Reels & Video Production',
      'Brand Positioning',
    ],
    colors: [
      { hex: '#001D39', name: 'Navy' },
      { hex: '#5A697A', name: 'Slate' },
      { hex: '#FFFFFF', name: 'White' },
    ],
    socialHandles: [],
    logo: '/assets/img/logos/Forevents logo.jpeg',
    socialPosts: [
      { type: 'post', image: '/assets/img/social media posts/post/optimized/forevents-products-furniture.webp', caption: 'Event furniture rental range' },
      { type: 'post', image: '/assets/img/social media posts/post/optimized/forevents-services.webp', caption: 'Corporate event services' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/forevents-furniture-collection.webp', video: '/assets/img/social media posts/video/optimized/forevents-furniture-collection.mp4', caption: 'Furniture setup in action' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/forevents-events-sfx- collections.webp', video: '/assets/img/social media posts/video/optimized/forevents-sfx-collections.mp4', caption: 'SFX collection walkthrough' },
      { type: 'reel', image: '/assets/img/social media posts/video/posters/for-events-intro.webp', video: '/assets/img/social media posts/video/optimized/for-events-intro.mp4', caption: 'Event brand introduction reel' },
    ],
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #0a1830 50%, #0d2a52 100%)',
    coverIcon: 'fa-calendar-days',
  },
  {
    id: 'venture-conclave',
    theme: 'noir-editorial',
    cat: ['Website', 'Social Media', 'Branding'],
    title: 'Venture Conclave',
    industry: 'Business Events & Networking',
    industryIcon: 'fa-handshake',
    tagline: 'An exclusive networking event for founders and investors, a ThinkSuite original.',
    desc: 'Venture Conclave is ThinkSuite\'s own curated networking event connecting serious founders and investors. We built the complete brand identity, event website, and promotional video content for this invite-only gathering focused on meaningful connections and real opportunities.',
    contribution: 'We designed and built Venture Conclave from the ground up: the brand identity (gold-and-black premium aesthetic), the event website, and the promotional video content used to drive registrations.',
    services: [
      'Brand Identity & Logo Design',
      'Website Design & Development',
      'Event Promotional Video',
      'Social Media Content',
    ],
    colors: [
      { hex: '#C79C4C', name: 'Gold' },
      { hex: '#0D0D0D', name: 'Black' },
      { hex: '#F3E1A9', name: 'Champagne' },
    ],
    socialHandles: [],
    logo: '/assets/img/logos/Venture conclave logo.png',
    screenshot: '/assets/img/projects images/optimized/venture-conclave.webp',
    socialPosts: [
      { type: 'reel', image: '/assets/img/social media posts/video/posters/venture-conclave.webp', video: '/assets/img/social media posts/video/optimized/venture-conclave.mp4', caption: 'Venture Conclave promotional reel' },
    ],
    coverGradient: 'linear-gradient(135deg, #07091a 0%, #1a1408 50%, #3d2f0a 100%)',
    coverIcon: 'fa-handshake',
  },
]

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find(p => p.id === slug)
}
