/**
 * Thinksuite Marketplace — Product Catalog
 * 30 industries × 14 departments × multiple roles = 2000+ potential products
 * This file contains the initial launch set.
 */

export const INDUSTRIES = [
  { id: "real-estate",      label: "Real Estate",             icon: "🏠" },
  { id: "healthcare",       label: "Healthcare / Clinic",     icon: "🏥" },
  { id: "ecommerce",        label: "E-commerce",              icon: "🛒" },
  { id: "restaurant",       label: "Restaurant / F&B",        icon: "🍽️" },
  { id: "education",        label: "Education / Coaching",    icon: "📚" },
  { id: "legal",            label: "Legal / Law Firm",        icon: "⚖️" },
  { id: "manufacturing",    label: "Manufacturing",           icon: "🏭" },
  { id: "it-software",      label: "IT / Software",           icon: "💻" },
  { id: "finance-ca",       label: "Finance / CA Firm",       icon: "📊" },
  { id: "retail",           label: "Retail / Dukaan",         icon: "🏪" },
  { id: "hotel",            label: "Hotel / Hospitality",     icon: "🏨" },
  { id: "automobile",       label: "Automobile / Car Dealer", icon: "🚗" },
  { id: "agriculture",      label: "Agriculture / Agritech",  icon: "🌾" },
  { id: "marketing-agency", label: "Marketing Agency",        icon: "📣" },
  { id: "logistics",        label: "Logistics / Courier",     icon: "🚚" },
  { id: "insurance",        label: "Insurance",               icon: "🛡️" },
  { id: "construction",     label: "Construction",            icon: "🏗️" },
  { id: "textile-fashion",  label: "Textile / Fashion",       icon: "👗" },
  { id: "pharma",           label: "Pharma / Medical Store",  icon: "💊" },
  { id: "events",           label: "Events Management",       icon: "🎪" },
  { id: "travel",           label: "Travel / Tourism",        icon: "✈️" },
  { id: "recruitment",      label: "Recruitment / Staffing",  icon: "🤝" },
  { id: "gym-fitness",      label: "Gym / Fitness",           icon: "💪" },
  { id: "salon-beauty",     label: "Salon / Beauty",          icon: "💅" },
  { id: "ngo",              label: "NGO / Non-profit",        icon: "❤️" },
];

export const DEPARTMENTS = [
  { id: "sales",       label: "Sales" },
  { id: "marketing",   label: "Marketing" },
  { id: "support",     label: "Customer Support" },
  { id: "hr",          label: "HR" },
  { id: "finance",     label: "Finance & Accounts" },
  { id: "operations",  label: "Operations" },
  { id: "legal",       label: "Legal & Compliance" },
];

/** @type {Product[]} */
export const PRODUCTS = [

  // ─── REAL ESTATE ──────────────────────────────────────────────────────────────

  {
    id: "real-estate-lead-agent",
    name: "Real Estate Lead Agent",
    industry: "real-estate",
    department: "sales",
    role: "Sales Executive",
    type: "agent",
    icon: "🏠",
    tagline: "99acres + MagicBricks leads every morning",
    description: "Automatically finds property buyers and sellers from 99acres, MagicBricks, Housing.com, and social media. Qualifies every lead with AI, sends WhatsApp follow-up, and tracks status in your CRM.",
    bullets: [
      "Scrapes 99acres, MagicBricks, Housing.com daily",
      "AI qualifies — genuine buyer vs casual enquiry",
      "Auto WhatsApp + email outreach on new leads",
      "Site visit scheduling and follow-up reminders",
      "Tracks lead journey from inquiry to possession",
    ],
    price_monthly: 2999,
    price_per_result: 20,
    result_unit: "lead",
    tags: ["99acres", "MagicBricks", "WhatsApp", "Auto Follow-up"],
    active_users: 312,
    success_rate: 93,
    seller: "mythink-official",
  },
  {
    id: "real-estate-marketing-employee",
    name: "Real Estate Marketing AI",
    industry: "real-estate",
    department: "marketing",
    role: "Marketing Manager",
    type: "employee",
    icon: "🏠",
    tagline: "Listings, ads, and content — fully automated",
    description: "Posts your properties across all platforms, runs Google and Meta ads, creates virtual tour scripts, and manages your Instagram and YouTube presence. One AI employee doing the work of a full marketing team.",
    bullets: [
      "Auto-post listings to 99acres, MagicBricks, OLX",
      "Google & Meta property ads management",
      "Instagram reels and YouTube description writing",
      "Locality reports and price trend content",
      "Virtual tour scripts and property brochures",
    ],
    price_monthly: 7999,
    price_per_result: null,
    result_unit: null,
    tags: ["Property Ads", "Instagram", "Content", "Listings"],
    active_users: 178,
    success_rate: 91,
    seller: "mythink-official",
  },
  {
    id: "real-estate-support-agent",
    name: "Real Estate Support Agent",
    industry: "real-estate",
    department: "support",
    role: "Customer Support Executive",
    type: "agent",
    icon: "🏠",
    tagline: "Answer buyer queries 24×7 on WhatsApp",
    description: "Handles buyer questions about RERA, home loans, possession timelines, society charges, and documentation. Available 24×7 on WhatsApp and your website.",
    bullets: [
      "RERA registration and compliance queries",
      "Home loan process guidance",
      "Possession timeline and documentation",
      "Complaint tracking and escalation",
      "24×7 WhatsApp + website chat",
    ],
    price_monthly: 1999,
    price_per_result: 5,
    result_unit: "query",
    tags: ["WhatsApp", "24×7", "RERA", "Home Loan"],
    active_users: 143,
    success_rate: 96,
    seller: "mythink-official",
  },
  {
    id: "real-estate-finance-employee",
    name: "Real Estate Finance AI",
    industry: "real-estate",
    department: "finance",
    role: "Finance Manager",
    type: "employee",
    icon: "🏠",
    tagline: "RERA payments, TDS, GST — fully tracked",
    description: "Tracks RERA payment schedules, manages builder payments, coordinates home loan documentation, calculates TDS on property, and handles GST for under-construction properties.",
    bullets: [
      "RERA payment schedule tracking and alerts",
      "TDS on property calculation and filing",
      "GST on under-construction property",
      "Home loan bank document follow-up",
      "Builder payment reconciliation",
    ],
    price_monthly: 5999,
    price_per_result: null,
    result_unit: null,
    tags: ["RERA", "TDS", "GST", "Home Loan"],
    active_users: 89,
    success_rate: 97,
    seller: "mythink-official",
  },

  // ─── HEALTHCARE ───────────────────────────────────────────────────────────────

  {
    id: "healthcare-support-employee",
    name: "Clinic Support AI",
    industry: "healthcare",
    department: "support",
    role: "Customer Support Executive",
    type: "employee",
    icon: "🏥",
    tagline: "Appointments, reports, reminders — automated",
    description: "Handles appointment bookings, sends test reports, medication reminders, and post-discharge follow-ups on WhatsApp. Covers OPD timings, doctor availability, and insurance queries.",
    bullets: [
      "WhatsApp appointment booking and rescheduling",
      "Test report delivery and explanation",
      "Medication and follow-up reminders",
      "Insurance query handling",
      "OPD timing, doctor availability info",
    ],
    price_monthly: 4999,
    price_per_result: 3,
    result_unit: "interaction",
    tags: ["Appointments", "WhatsApp", "Reports", "Insurance"],
    active_users: 267,
    success_rate: 95,
    seller: "mythink-official",
  },
  {
    id: "healthcare-marketing-agent",
    name: "Healthcare Marketing Agent",
    industry: "healthcare",
    department: "marketing",
    role: "Social Media Manager",
    type: "agent",
    icon: "🏥",
    tagline: "Health tips, doctor profiles, camp promotions daily",
    description: "Publishes daily health tip content on Instagram and Facebook, promotes doctor profiles, announces health camps, and optimizes your Google Business listing for local searches.",
    bullets: [
      "Daily health tips for Instagram & Facebook",
      "Doctor profile and achievements posts",
      "Health camp and event promotions",
      "Google Business listing optimization",
      "Patient testimonial content creation",
    ],
    price_monthly: 1999,
    price_per_result: 10,
    result_unit: "post",
    tags: ["Instagram", "Health Tips", "Google Business", "Campaigns"],
    active_users: 198,
    success_rate: 90,
    seller: "mythink-official",
  },
  {
    id: "healthcare-lead-agent",
    name: "Healthcare Sales Agent",
    industry: "healthcare",
    department: "sales",
    role: "Sales Executive",
    type: "agent",
    icon: "🏥",
    tagline: "Corporate health packages and insurance tie-ups",
    description: "Identifies corporate clients for health package deals, handles insurance empanelment applications, and reaches out to companies for annual health check-up contracts.",
    bullets: [
      "Corporate health package lead generation",
      "Insurance company empanelment process",
      "Medical tourism inquiry handling",
      "Doctor referral network building",
      "Health camp B2B outreach",
    ],
    price_monthly: 2499,
    price_per_result: 30,
    result_unit: "lead",
    tags: ["Corporate", "Insurance", "B2B", "Health Packages"],
    active_users: 112,
    success_rate: 88,
    seller: "mythink-official",
  },

  // ─── E-COMMERCE ───────────────────────────────────────────────────────────────

  {
    id: "ecommerce-marketing-employee",
    name: "E-commerce Marketing AI",
    industry: "ecommerce",
    department: "marketing",
    role: "Marketing Manager",
    type: "employee",
    icon: "🛒",
    tagline: "Amazon, Flipkart, Meesho — listings optimized daily",
    description: "Optimizes product listings on Amazon, Flipkart, and Meesho with AI-written descriptions and keywords. Manages social media product posts, runs influencer outreach, and creates sale event banners.",
    bullets: [
      "Amazon, Flipkart, Meesho listing optimization",
      "AI-written product descriptions and keywords",
      "Social media product posts on schedule",
      "Influencer outreach for product promotion",
      "Sale event banners and campaign content",
    ],
    price_monthly: 5999,
    price_per_result: null,
    result_unit: null,
    tags: ["Amazon", "Flipkart", "Meesho", "SEO", "Influencer"],
    active_users: 445,
    success_rate: 92,
    seller: "mythink-official",
  },
  {
    id: "ecommerce-support-agent",
    name: "E-commerce Support Agent",
    industry: "ecommerce",
    department: "support",
    role: "Support Executive",
    type: "agent",
    icon: "🛒",
    tagline: "Order, return, refund queries — zero human effort",
    description: "Handles order status, returns, refunds, exchanges, and product queries automatically. Responds to negative marketplace reviews and manages complaint escalations.",
    bullets: [
      "Order status and delivery tracking",
      "Return, refund, and exchange processing",
      "Negative review response on Amazon/Flipkart",
      "Product specification queries",
      "Complaint escalation management",
    ],
    price_monthly: 1999,
    price_per_result: 2,
    result_unit: "query",
    tags: ["Returns", "Refunds", "Order Status", "Reviews"],
    active_users: 389,
    success_rate: 94,
    seller: "mythink-official",
  },
  {
    id: "ecommerce-operations-agent",
    name: "Inventory & Operations Agent",
    industry: "ecommerce",
    department: "operations",
    role: "Operations Manager",
    type: "agent",
    icon: "🛒",
    tagline: "Low stock alerts, reorder, and courier tracking",
    description: "Monitors inventory across all warehouses, sends low-stock alerts, coordinates reorder with vendors, tracks courier partners, and manages return processing workflows.",
    bullets: [
      "Real-time inventory monitoring across warehouses",
      "Low stock alerts and auto reorder triggers",
      "Courier partner shipment tracking",
      "Return processing coordination",
      "Marketplace compliance check",
    ],
    price_monthly: 2499,
    price_per_result: null,
    result_unit: null,
    tags: ["Inventory", "Courier", "Returns", "Reorder"],
    active_users: 234,
    success_rate: 97,
    seller: "mythink-official",
  },

  // ─── RESTAURANT ───────────────────────────────────────────────────────────────

  {
    id: "restaurant-marketing-agent",
    name: "Restaurant Marketing Agent",
    industry: "restaurant",
    department: "marketing",
    role: "Social Media Manager",
    type: "agent",
    icon: "🍽️",
    tagline: "Zomato, Swiggy, Instagram — all managed daily",
    description: "Optimizes your Zomato and Swiggy listings, posts daily food content on Instagram, creates festival offers, and runs Google review campaigns to keep your ratings high.",
    bullets: [
      "Zomato and Swiggy listing optimization",
      "Daily specials and food content for Instagram",
      "Festival offer creation and promotion",
      "Google review response and campaigns",
      "Menu item performance analysis",
    ],
    price_monthly: 1999,
    price_per_result: 8,
    result_unit: "post",
    tags: ["Zomato", "Swiggy", "Instagram", "Reviews"],
    active_users: 521,
    success_rate: 91,
    seller: "mythink-official",
  },
  {
    id: "restaurant-support-agent",
    name: "Restaurant Reservation Agent",
    industry: "restaurant",
    department: "support",
    role: "Support Executive",
    type: "agent",
    icon: "🍽️",
    tagline: "Table bookings, orders, complaints on WhatsApp",
    description: "Manages table reservations, delivery order queries, complaint handling, and feedback collection on WhatsApp. Coordinates special occasion arrangements without any manual effort.",
    bullets: [
      "WhatsApp table reservation management",
      "Delivery order status and queries",
      "Complaint handling and resolution",
      "Special occasion coordination (birthday, anniversary)",
      "Customer feedback collection",
    ],
    price_monthly: 1499,
    price_per_result: 3,
    result_unit: "booking",
    tags: ["WhatsApp", "Reservations", "Delivery", "Feedback"],
    active_users: 378,
    success_rate: 94,
    seller: "mythink-official",
  },
  {
    id: "restaurant-finance-agent",
    name: "Restaurant Finance Agent",
    industry: "restaurant",
    department: "finance",
    role: "Accountant",
    type: "agent",
    icon: "🍽️",
    tagline: "Daily cash reconciliation and food cost tracking",
    description: "Reconciles daily cash and Zomato/Swiggy payouts, calculates food cost per dish, tracks vendor payments, prepares GST filing data, and generates daily profit reports.",
    bullets: [
      "Daily cash and POS reconciliation",
      "Zomato/Swiggy payout reconciliation",
      "Food cost per dish calculation",
      "Vendor payment tracking",
      "GST filing data preparation",
    ],
    price_monthly: 2499,
    price_per_result: null,
    result_unit: null,
    tags: ["Cash Reconciliation", "GST", "Food Cost", "Zomato Payout"],
    active_users: 189,
    success_rate: 96,
    seller: "mythink-official",
  },

  // ─── EDUCATION ────────────────────────────────────────────────────────────────

  {
    id: "education-sales-agent",
    name: "Coaching Admissions Agent",
    industry: "education",
    department: "sales",
    role: "Sales Executive",
    type: "agent",
    icon: "📚",
    tagline: "Student leads, demo calls, parent follow-ups",
    description: "Finds student leads from social media and education portals, schedules demo classes, follows up with parents, and handles scholarship inquiries — all automated.",
    bullets: [
      "Student lead generation from social media",
      "Demo class scheduling and reminders",
      "Parent WhatsApp follow-up sequences",
      "Scholarship inquiry handling",
      "School and college partnership outreach",
    ],
    price_monthly: 2499,
    price_per_result: 25,
    result_unit: "lead",
    tags: ["Student Leads", "Demo Classes", "Parent Follow-up", "WhatsApp"],
    active_users: 334,
    success_rate: 89,
    seller: "mythink-official",
  },
  {
    id: "education-marketing-agent",
    name: "Education Marketing Agent",
    industry: "education",
    department: "marketing",
    role: "Content Marketer",
    type: "agent",
    icon: "📚",
    tagline: "Result posts, YouTube scripts, and Google ads",
    description: "Creates result announcement posts, student success stories, YouTube video scripts, and runs Google and Facebook ads targeting students in your city.",
    bullets: [
      "Result and topper announcement posts",
      "Student success story content",
      "YouTube shorts and video scripts",
      "Google and Facebook student acquisition ads",
      "Webinar and free class promotions",
    ],
    price_monthly: 1999,
    price_per_result: 10,
    result_unit: "post",
    tags: ["Results", "YouTube", "Ads", "Webinar"],
    active_users: 267,
    success_rate: 90,
    seller: "mythink-official",
  },
  {
    id: "education-support-agent",
    name: "Education Support Agent",
    industry: "education",
    department: "support",
    role: "Support Executive",
    type: "agent",
    icon: "📚",
    tagline: "Admission process, fee, schedule — answered instantly",
    description: "Handles admission process queries, fee structure, schedule and timetable sharing, parent queries, and certificate/document requests on WhatsApp 24×7.",
    bullets: [
      "Admission process and eligibility queries",
      "Fee structure and EMI information",
      "Class schedule and timetable sharing",
      "Certificate and document request processing",
      "24×7 WhatsApp support",
    ],
    price_monthly: 1499,
    price_per_result: 2,
    result_unit: "query",
    tags: ["Admissions", "Fee Queries", "WhatsApp", "24×7"],
    active_users: 445,
    success_rate: 95,
    seller: "mythink-official",
  },

  // ─── LEGAL ────────────────────────────────────────────────────────────────────

  {
    id: "legal-support-agent",
    name: "Law Firm Client Agent",
    industry: "legal",
    department: "support",
    role: "Support Executive",
    type: "agent",
    icon: "⚖️",
    tagline: "Case updates, court dates, document reminders",
    description: "Sends case status updates, court date reminders, document requirement lists, and handles basic legal query routing — so your team focuses on practice, not client calls.",
    bullets: [
      "Case status update to clients on WhatsApp",
      "Court date reminders (client + lawyer)",
      "Document requirement list delivery",
      "Basic legal query routing",
      "Appointment scheduling for consultations",
    ],
    price_monthly: 2499,
    price_per_result: 5,
    result_unit: "interaction",
    tags: ["Case Updates", "Court Dates", "WhatsApp", "Documents"],
    active_users: 145,
    success_rate: 96,
    seller: "mythink-official",
  },
  {
    id: "legal-marketing-agent",
    name: "Law Firm Marketing Agent",
    industry: "legal",
    department: "marketing",
    role: "Content Manager",
    type: "agent",
    icon: "⚖️",
    tagline: "Legal awareness content for LinkedIn and Instagram",
    description: "Creates Bar Council-compliant legal awareness posts, case study content, and LinkedIn thought leadership articles to build your firm's online reputation.",
    bullets: [
      "Legal awareness posts for Instagram and LinkedIn",
      "Case study content (anonymized)",
      "LinkedIn firm profile management",
      "Bar Council compliant marketing content",
      "Legal FAQ blog posts for Google ranking",
    ],
    price_monthly: 1999,
    price_per_result: 8,
    result_unit: "post",
    tags: ["LinkedIn", "Legal Awareness", "Bar Council", "Blog"],
    active_users: 98,
    success_rate: 91,
    seller: "mythink-official",
  },

  // ─── MANUFACTURING ────────────────────────────────────────────────────────────

  {
    id: "manufacturing-sales-agent",
    name: "Manufacturing Sales Agent",
    industry: "manufacturing",
    department: "sales",
    role: "Sales Executive",
    type: "agent",
    icon: "🏭",
    tagline: "B2B buyers, distributors, and tender tracking",
    description: "Finds B2B buyers on IndiaMART and TradeIndia, develops distributor leads, handles export inquiries, and tracks relevant government tenders for your products.",
    bullets: [
      "IndiaMART and TradeIndia buyer leads",
      "Distributor network development",
      "Export inquiry handling",
      "Government tender tracking and alerts",
      "Auto follow-up on B2B inquiries",
    ],
    price_monthly: 3499,
    price_per_result: 30,
    result_unit: "lead",
    tags: ["IndiaMART", "B2B", "Tenders", "Export", "Distributors"],
    active_users: 198,
    success_rate: 87,
    seller: "mythink-official",
  },
  {
    id: "manufacturing-operations-employee",
    name: "Manufacturing Operations AI",
    industry: "manufacturing",
    department: "operations",
    role: "Operations Manager",
    type: "employee",
    icon: "🏭",
    tagline: "Production schedule, inventory, dispatch — managed",
    description: "Manages production scheduling, raw material inventory with low-stock alerts, machine maintenance calendar, quality control checklists, and dispatch planning.",
    bullets: [
      "Production schedule creation and tracking",
      "Raw material inventory with low-stock alerts",
      "Machine maintenance scheduling",
      "Quality control checklist management",
      "Dispatch planning and coordination",
    ],
    price_monthly: 8999,
    price_per_result: null,
    result_unit: null,
    tags: ["Production", "Inventory", "Maintenance", "Dispatch", "QC"],
    active_users: 134,
    success_rate: 94,
    seller: "mythink-official",
  },
  {
    id: "manufacturing-hr-agent",
    name: "Factory HR Agent",
    industry: "manufacturing",
    department: "hr",
    role: "HR Executive",
    type: "agent",
    icon: "🏭",
    tagline: "Worker recruitment, attendance, PF/ESI compliance",
    description: "Recruits factory workers, manages shift schedules, tracks attendance and overtime, and handles PF/ESI compliance — the complete HR function for manufacturing units.",
    bullets: [
      "Factory worker recruitment and screening",
      "Shift schedule management",
      "Attendance and overtime tracking",
      "PF/ESI compliance management",
      "Labour law compliance alerts",
    ],
    price_monthly: 2999,
    price_per_result: null,
    result_unit: null,
    tags: ["Recruitment", "Attendance", "PF", "ESI", "Shift"],
    active_users: 167,
    success_rate: 93,
    seller: "mythink-official",
  },

  // ─── IT / SOFTWARE ────────────────────────────────────────────────────────────

  {
    id: "it-sales-agent",
    name: "IT Sales Agent",
    industry: "it-software",
    department: "sales",
    role: "BDM",
    type: "agent",
    icon: "💻",
    tagline: "LinkedIn tech leads, demos, proposals automated",
    description: "Finds tech decision-makers on LinkedIn, schedules product demos, drafts proposals and SOWs, and manages international client outreach — automating your entire B2B sales funnel.",
    bullets: [
      "LinkedIn tech lead generation",
      "Demo scheduling and follow-up",
      "Proposal and SOW drafting",
      "Enterprise account outreach",
      "International client email campaigns",
    ],
    price_monthly: 4499,
    price_per_result: 40,
    result_unit: "lead",
    tags: ["LinkedIn", "Enterprise", "Proposals", "International", "B2B"],
    active_users: 223,
    success_rate: 86,
    seller: "mythink-official",
  },
  {
    id: "it-marketing-employee",
    name: "IT Marketing AI",
    industry: "it-software",
    department: "marketing",
    role: "Content Marketer",
    type: "employee",
    icon: "💻",
    tagline: "Tech blogs, case studies, LinkedIn thought leadership",
    description: "Writes technical blog posts, creates client case studies, manages LinkedIn thought leadership content, promotes webinars, and handles SEO technical content — full-time marketing output.",
    bullets: [
      "Technical blog posts (1000+ words)",
      "Client case study content",
      "LinkedIn thought leadership posts",
      "Webinar and event promotion",
      "SEO-optimized technical content",
    ],
    price_monthly: 6999,
    price_per_result: null,
    result_unit: null,
    tags: ["LinkedIn", "Blog", "Case Studies", "SEO", "Webinar"],
    active_users: 189,
    success_rate: 91,
    seller: "mythink-official",
  },
  {
    id: "it-hr-agent",
    name: "Tech HR Agent",
    industry: "it-software",
    department: "hr",
    role: "Recruiter",
    type: "agent",
    icon: "💻",
    tagline: "Developer recruitment from Naukri and LinkedIn",
    description: "Finds developers, designers, and QA engineers from Naukri and LinkedIn, coordinates technical assessments, generates offer letters, and tracks attrition patterns.",
    bullets: [
      "Developer and designer sourcing",
      "Naukri and LinkedIn candidate search",
      "Technical assessment coordination",
      "Offer letter generation",
      "Attrition tracking and analysis",
    ],
    price_monthly: 3499,
    price_per_result: 50,
    result_unit: "candidate",
    tags: ["Naukri", "LinkedIn", "Developers", "Recruitment", "Offer Letter"],
    active_users: 156,
    success_rate: 88,
    seller: "mythink-official",
  },

  // ─── FINANCE / CA ─────────────────────────────────────────────────────────────

  {
    id: "finance-operations-employee",
    name: "CA Firm Compliance AI",
    industry: "finance-ca",
    department: "operations",
    role: "Compliance Manager",
    type: "employee",
    icon: "📊",
    tagline: "GST, ITR, ROC deadlines — never miss a date",
    description: "Manages your complete compliance calendar — GST filing dates, ITR deadlines, ROC filings, and TDS due dates. Sends client reminders, tracks document collection, and monitors filing status.",
    bullets: [
      "GST, ITR, ROC, TDS compliance calendar",
      "Client document collection follow-up",
      "Filing status tracking per client",
      "Compliance deadline alerts (client + CA)",
      "Auto-reminder to clients via WhatsApp",
    ],
    price_monthly: 5999,
    price_per_result: null,
    result_unit: null,
    tags: ["GST", "ITR", "ROC", "TDS", "Compliance Calendar"],
    active_users: 267,
    success_rate: 97,
    seller: "mythink-official",
  },
  {
    id: "finance-marketing-agent",
    name: "CA Firm Marketing Agent",
    industry: "finance-ca",
    department: "marketing",
    role: "Content Manager",
    type: "agent",
    icon: "📊",
    tagline: "Tax tips, deadline reminders, YouTube shorts daily",
    description: "Posts tax tips, compliance deadline reminders, and financial advice on social media. Creates YouTube shorts scripts on tax-saving strategies and builds your firm's digital presence.",
    bullets: [
      "Daily tax tips for Instagram and LinkedIn",
      "Compliance deadline reminder posts",
      "YouTube shorts scripts on tax topics",
      "Client testimonial content",
      "Seasonal campaign content (tax season, audit season)",
    ],
    price_monthly: 1999,
    price_per_result: 8,
    result_unit: "post",
    tags: ["Tax Tips", "LinkedIn", "YouTube", "Instagram"],
    active_users: 178,
    success_rate: 92,
    seller: "mythink-official",
  },

  // ─── RETAIL ───────────────────────────────────────────────────────────────────

  {
    id: "retail-marketing-agent",
    name: "Retail WhatsApp Marketing Agent",
    industry: "retail",
    department: "marketing",
    role: "Marketing Executive",
    type: "agent",
    icon: "🏪",
    tagline: "WhatsApp broadcasts, offers, new arrivals daily",
    description: "Sends WhatsApp broadcast messages for offers and new arrivals, creates Instagram product posts, updates Google My Business listing, and designs festival offer campaigns.",
    bullets: [
      "WhatsApp broadcast for offers and new stock",
      "Instagram product posts and reels",
      "Google My Business listing updates",
      "Festival and seasonal offer design",
      "Customer loyalty program messages",
    ],
    price_monthly: 1499,
    price_per_result: 5,
    result_unit: "message",
    tags: ["WhatsApp", "Instagram", "Google My Business", "Offers"],
    active_users: 623,
    success_rate: 93,
    seller: "mythink-official",
  },
  {
    id: "retail-operations-agent",
    name: "Retail Inventory Agent",
    industry: "retail",
    department: "operations",
    role: "Store Manager",
    type: "agent",
    icon: "🏪",
    tagline: "Low stock alerts, expiry tracking, reorder automation",
    description: "Tracks inventory levels, sends low-stock alerts, monitors expiry dates, coordinates reorders with vendors, and analyzes sales trends to optimize stock.",
    bullets: [
      "Real-time inventory tracking",
      "Low stock and out-of-stock alerts",
      "Expiry date monitoring and alerts",
      "Vendor reorder coordination",
      "Sales trend analysis by category",
    ],
    price_monthly: 1999,
    price_per_result: null,
    result_unit: null,
    tags: ["Inventory", "Expiry", "Reorder", "Stock Alerts"],
    active_users: 445,
    success_rate: 96,
    seller: "mythink-official",
  },

  // ─── HOTEL / HOSPITALITY ──────────────────────────────────────────────────────

  {
    id: "hotel-support-employee",
    name: "Hotel Guest Experience AI",
    industry: "hotel",
    department: "support",
    role: "Guest Relations Executive",
    type: "employee",
    icon: "🏨",
    tagline: "Bookings, check-in, room service — all on WhatsApp",
    description: "Handles room booking inquiries, check-in/out coordination, room service requests, complaint resolution, and post-stay feedback on WhatsApp and your website.",
    bullets: [
      "Room booking inquiry and availability",
      "Check-in/out coordination",
      "Room service and amenity requests",
      "Guest complaint resolution",
      "Post-stay feedback and review requests",
    ],
    price_monthly: 4999,
    price_per_result: null,
    result_unit: null,
    tags: ["WhatsApp", "Bookings", "Guest Relations", "Room Service"],
    active_users: 234,
    success_rate: 94,
    seller: "mythink-official",
  },
  {
    id: "hotel-marketing-agent",
    name: "Hotel Marketing Agent",
    industry: "hotel",
    department: "marketing",
    role: "Marketing Manager",
    type: "agent",
    icon: "🏨",
    tagline: "MakeMyTrip, OYO, Instagram — all managed",
    description: "Manages your hotel listings on MakeMyTrip, OYO, and Booking.com, creates Instagram content showcasing rooms and amenities, and runs seasonal promotional campaigns.",
    bullets: [
      "MakeMyTrip, OYO, Booking.com listing management",
      "Instagram room and amenity content",
      "Seasonal package promotion campaigns",
      "Review response management",
      "Wedding and event package outreach",
    ],
    price_monthly: 2999,
    price_per_result: null,
    result_unit: null,
    tags: ["MakeMyTrip", "OYO", "Instagram", "Events", "Reviews"],
    active_users: 167,
    success_rate: 90,
    seller: "mythink-official",
  },

  // ─── AUTOMOBILE ───────────────────────────────────────────────────────────────

  {
    id: "automobile-sales-agent",
    name: "Car Dealership Sales Agent",
    industry: "automobile",
    department: "sales",
    role: "Sales Executive",
    type: "agent",
    icon: "🚗",
    tagline: "Test drive bookings, EMI calculations, lead follow-up",
    description: "Captures showroom inquiries, books test drives, provides EMI calculations, follows up with leads on WhatsApp, and tracks the entire buyer journey from inquiry to delivery.",
    bullets: [
      "Showroom inquiry capture and qualification",
      "Test drive booking automation",
      "EMI and loan option calculations",
      "WhatsApp follow-up sequences",
      "Delivery date and documentation reminders",
    ],
    price_monthly: 3499,
    price_per_result: 35,
    result_unit: "lead",
    tags: ["Test Drive", "EMI", "WhatsApp", "Car Loans", "Follow-up"],
    active_users: 189,
    success_rate: 90,
    seller: "mythink-official",
  },

  // ─── MARKETING AGENCY ─────────────────────────────────────────────────────────

  {
    id: "agency-sales-agent",
    name: "Agency New Business Agent",
    industry: "marketing-agency",
    department: "sales",
    role: "BDM",
    type: "agent",
    icon: "📣",
    tagline: "Client prospecting, pitch decks, and proposal follow-up",
    description: "Finds potential clients on LinkedIn and JustDial, automates pitch outreach, creates proposal follow-up sequences, and tracks your agency's new business pipeline.",
    bullets: [
      "LinkedIn and JustDial client prospecting",
      "Cold email and WhatsApp pitch sequences",
      "Proposal follow-up automation",
      "New business pipeline tracking",
      "Industry-specific outreach campaigns",
    ],
    price_monthly: 3999,
    price_per_result: 40,
    result_unit: "lead",
    tags: ["LinkedIn", "Pitches", "New Business", "Proposals"],
    active_users: 145,
    success_rate: 85,
    seller: "mythink-official",
  },
  {
    id: "agency-hr-agent",
    name: "Agency HR Agent",
    industry: "marketing-agency",
    department: "hr",
    role: "HR Manager",
    type: "agent",
    icon: "📣",
    tagline: "Creative talent recruitment and freelancer management",
    description: "Sources designers, copywriters, and social media managers from LinkedIn, Behance, and Naukri. Manages freelancer contracts, deadlines, and payments.",
    bullets: [
      "Designer and copywriter sourcing",
      "Freelancer contract and deadline management",
      "Internship program coordination",
      "Payroll for in-house + freelancers",
      "Performance review scheduling",
    ],
    price_monthly: 2499,
    price_per_result: 40,
    result_unit: "candidate",
    tags: ["Freelancers", "Designers", "Recruitment", "Contracts"],
    active_users: 112,
    success_rate: 88,
    seller: "mythink-official",
  },

  // ─── LOGISTICS ────────────────────────────────────────────────────────────────

  {
    id: "logistics-support-agent",
    name: "Logistics Customer Agent",
    industry: "logistics",
    department: "support",
    role: "Support Executive",
    type: "agent",
    icon: "🚚",
    tagline: "Shipment tracking, delays, delivery queries automated",
    description: "Handles shipment tracking queries, delivery delay notifications, damage claims, and POD requests on WhatsApp — reducing your support team's workload by 80%.",
    bullets: [
      "Real-time shipment status on WhatsApp",
      "Delay notification with ETA update",
      "Damage claim initiation and tracking",
      "POD request and delivery confirmation",
      "Bulk tracking for B2B clients",
    ],
    price_monthly: 2499,
    price_per_result: 2,
    result_unit: "query",
    tags: ["Tracking", "WhatsApp", "Delays", "Claims", "POD"],
    active_users: 312,
    success_rate: 95,
    seller: "mythink-official",
  },

  // ─── GYM / FITNESS ────────────────────────────────────────────────────────────

  {
    id: "gym-marketing-agent",
    name: "Gym Marketing Agent",
    industry: "gym-fitness",
    department: "marketing",
    role: "Marketing Executive",
    type: "agent",
    icon: "💪",
    tagline: "Transformation posts, challenges, and membership drives",
    description: "Creates before/after transformation content, fitness challenge campaigns, membership offer posts, and manages your gym's Instagram and Google My Business presence.",
    bullets: [
      "Transformation story content for Instagram",
      "Monthly fitness challenge campaigns",
      "Membership offer and discount posts",
      "Google My Business optimization",
      "YouTube shorts workout tip scripts",
    ],
    price_monthly: 1499,
    price_per_result: 6,
    result_unit: "post",
    tags: ["Instagram", "Transformations", "Challenges", "Membership"],
    active_users: 289,
    success_rate: 90,
    seller: "mythink-official",
  },
  {
    id: "gym-support-agent",
    name: "Gym Member Support Agent",
    industry: "gym-fitness",
    department: "support",
    role: "Support Executive",
    type: "agent",
    icon: "💪",
    tagline: "Membership, schedule, renewals on WhatsApp",
    description: "Handles membership inquiries, class schedule sharing, renewal reminders, batch queries, and PT session bookings on WhatsApp — 24×7.",
    bullets: [
      "Membership fee and plan queries",
      "Class and batch schedule sharing",
      "Renewal reminder 15 days in advance",
      "Personal trainer session booking",
      "Nutrition and supplement queries routing",
    ],
    price_monthly: 1499,
    price_per_result: 2,
    result_unit: "interaction",
    tags: ["WhatsApp", "Renewals", "Schedule", "PT Sessions"],
    active_users: 378,
    success_rate: 94,
    seller: "mythink-official",
  },

  // ─── SALON / BEAUTY ───────────────────────────────────────────────────────────

  {
    id: "salon-support-agent",
    name: "Salon Booking Agent",
    industry: "salon-beauty",
    department: "support",
    role: "Receptionist",
    type: "agent",
    icon: "💅",
    tagline: "Appointments, reminders, and service queries on WhatsApp",
    description: "Books salon appointments, sends confirmation and reminder messages, handles service queries, and manages cancellations and rescheduling — all on WhatsApp.",
    bullets: [
      "WhatsApp appointment booking",
      "Confirmation and reminder messages",
      "Service menu and pricing queries",
      "Cancellation and rescheduling",
      "Loyalty points and offer notifications",
    ],
    price_monthly: 1499,
    price_per_result: 2,
    result_unit: "booking",
    tags: ["WhatsApp", "Appointments", "Reminders", "Services"],
    active_users: 456,
    success_rate: 95,
    seller: "mythink-official",
  },
  {
    id: "salon-marketing-agent",
    name: "Salon Marketing Agent",
    industry: "salon-beauty",
    department: "marketing",
    role: "Social Media Manager",
    type: "agent",
    icon: "💅",
    tagline: "Before/after posts, offers, and Google reviews",
    description: "Creates before/after transformation content, posts seasonal beauty offers, responds to Google reviews, and manages your salon's Instagram presence to attract new walk-ins.",
    bullets: [
      "Before/after transformation posts",
      "Seasonal beauty and bridal offer campaigns",
      "Google review response and management",
      "Instagram reels for hair and beauty",
      "Festival makeup and mehendi promotions",
    ],
    price_monthly: 1499,
    price_per_result: 6,
    result_unit: "post",
    tags: ["Instagram", "Before/After", "Google Reviews", "Offers"],
    active_users: 512,
    success_rate: 91,
    seller: "mythink-official",
  },

  // ─── TRAVEL / TOURISM ─────────────────────────────────────────────────────────

  {
    id: "travel-sales-agent",
    name: "Travel Sales Agent",
    industry: "travel",
    department: "sales",
    role: "Sales Executive",
    type: "agent",
    icon: "✈️",
    tagline: "Package inquiries, itineraries, and booking follow-ups",
    description: "Handles travel package inquiries, creates customized itinerary PDFs, follows up on pending bookings, and manages group tour lead pipelines.",
    bullets: [
      "Travel package inquiry handling",
      "Customized itinerary generation",
      "Booking follow-up automation",
      "Group tour lead management",
      "Visa and documentation guidance",
    ],
    price_monthly: 2999,
    price_per_result: 30,
    result_unit: "inquiry",
    tags: ["Itineraries", "Group Tours", "Bookings", "Visa"],
    active_users: 234,
    success_rate: 89,
    seller: "mythink-official",
  },

  // ─── RECRUITMENT ──────────────────────────────────────────────────────────────

  {
    id: "recruitment-hr-employee",
    name: "Staffing Agency AI",
    industry: "recruitment",
    department: "hr",
    role: "Recruiter",
    type: "employee",
    icon: "🤝",
    tagline: "Candidates, clients, and placements — fully managed",
    description: "Sources candidates from Naukri, LinkedIn, and referrals; matches them to client requirements; schedules interviews; and tracks placements and fees — the complete staffing workflow.",
    bullets: [
      "Candidate sourcing from Naukri and LinkedIn",
      "JD-to-candidate matching with AI",
      "Interview scheduling coordination",
      "Placement tracking and fee management",
      "Client requirement follow-up",
    ],
    price_monthly: 7999,
    price_per_result: 200,
    result_unit: "placement",
    tags: ["Naukri", "LinkedIn", "Placements", "Matching", "Interviews"],
    active_users: 156,
    success_rate: 87,
    seller: "mythink-official",
  },

  // ─── NGO ──────────────────────────────────────────────────────────────────────

  {
    id: "ngo-marketing-agent",
    name: "NGO Donor Outreach Agent",
    industry: "ngo",
    department: "marketing",
    role: "Communications Manager",
    type: "agent",
    icon: "❤️",
    tagline: "Impact stories, donor campaigns, and CSR outreach",
    description: "Creates impact story content, runs donation campaigns on social media, handles CSR partnership outreach, and sends donor thank-you and update messages.",
    bullets: [
      "Impact story content for social media",
      "Donation campaign management",
      "CSR partnership outreach to companies",
      "Donor thank-you and update messages",
      "Annual report content creation",
    ],
    price_monthly: 999,
    price_per_result: 5,
    result_unit: "outreach",
    tags: ["Donors", "Impact Stories", "CSR", "Campaigns"],
    active_users: 89,
    success_rate: 88,
    seller: "mythink-official",
  },
];

/** Helper — filter products */
export function getProducts({ industry, department, type, search } = {}) {
  let list = PRODUCTS;
  if (industry)   list = list.filter(p => p.industry === industry);
  if (department) list = list.filter(p => p.department === department);
  if (type)       list = list.filter(p => p.type === type);
  if (search) {
    const q = search.toLowerCase();
    list = list.filter(p =>
      p.name.toLowerCase().includes(q) ||
      p.tagline.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some(t => t.toLowerCase().includes(q))
    );
  }
  return list;
}

export function getProduct(id) {
  return PRODUCTS.find(p => p.id === id) || null;
}

export function getIndustry(id) {
  return INDUSTRIES.find(i => i.id === id) || null;
}
