// Shared lookup data used across lead-gen feature components

export const STATES = [
  "Andaman & Nicobar","Andhra Pradesh","Arunachal Pradesh","Assam","Bihar",
  "Chandigarh","Chhattisgarh","Dadra & Nagar Haveli","Delhi","Goa",
  "Gujarat","Haryana","Himachal Pradesh","Jammu & Kashmir","Jharkhand",
  "Karnataka","Kerala","Ladakh","Lakshadweep","Madhya Pradesh",
  "Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha",
  "Puducherry","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana",
  "Tripura","Uttar Pradesh","Uttarakhand","West Bengal",
];

export const STATE_CITIES = {
  "Andhra Pradesh":       ["Visakhapatnam","Vijayawada","Guntur","Nellore","Kurnool","Kakinada","Tirupati","Rajahmundry","Kadapa","Anantapur","Eluru","Ongole"],
  "Arunachal Pradesh":    ["Itanagar","Naharlagun","Pasighat","Tawang","Ziro"],
  "Assam":                ["Guwahati","Silchar","Dibrugarh","Jorhat","Nagaon","Tinsukia","Lakhimpur","Tezpur"],
  "Bihar":                ["Patna","Gaya","Muzaffarpur","Bhagalpur","Purnia","Ara","Begusarai","Katihar","Munger","Saharsa","Darbhanga","Hajipur"],
  "Chhattisgarh":         ["Raipur","Bhilai","Bilaspur","Durg","Korba","Rajnandgaon","Jagdalpur","Raigarh"],
  "Goa":                  ["Panaji","Vasco da Gama","Margao","Mapusa","Ponda","Calangute"],
  "Gujarat":              ["Ahmedabad","Surat","Vadodara","Rajkot","Bhavnagar","Jamnagar","Junagadh","Gandhinagar","Anand","Navsari","Morbi","Mehsana"],
  "Haryana":              ["Faridabad","Gurgaon","Panipat","Ambala","Hisar","Rohtak","Karnal","Sonipat","Panchkula","Yamunanagar","Rewari","Sirsa"],
  "Himachal Pradesh":     ["Shimla","Dharamshala","Solan","Mandi","Kullu","Manali","Baddi","Palampur"],
  "Jharkhand":            ["Ranchi","Jamshedpur","Dhanbad","Bokaro","Hazaribagh","Deoghar","Giridih","Ramgarh"],
  "Karnataka":            ["Bangalore","Mysore","Mangalore","Hubli","Belgaum","Dharwad","Tumkur","Shimoga","Gulbarga","Bidar","Bijapur","Udupi"],
  "Kerala":               ["Thiruvananthapuram","Kochi","Kozhikode","Thrissur","Kollam","Malappuram","Palakkad","Alappuzha","Kannur","Kottayam"],
  "Madhya Pradesh":       ["Indore","Bhopal","Jabalpur","Gwalior","Ujjain","Sagar","Dewas","Satna","Ratlam","Rewa","Burhanpur","Khandwa"],
  "Maharashtra":          ["Mumbai","Pune","Nagpur","Nashik","Aurangabad","Solapur","Amravati","Nanded","Kolhapur","Thane","Navi Mumbai","Akola"],
  "Manipur":              ["Imphal","Thoubal","Bishnupur","Churachandpur"],
  "Meghalaya":            ["Shillong","Tura","Jowai","Nongpoh"],
  "Mizoram":              ["Aizawl","Lunglei","Champhai"],
  "Nagaland":             ["Kohima","Dimapur","Mokokchung"],
  "Odisha":               ["Bhubaneswar","Cuttack","Rourkela","Brahmapur","Sambalpur","Puri","Balasore","Bhadrak","Baripada"],
  "Punjab":               ["Ludhiana","Amritsar","Jalandhar","Patiala","Bathinda","Mohali","Hoshiarpur","Pathankot","Moga","Firozpur"],
  "Rajasthan":            ["Jaipur","Jodhpur","Kota","Bikaner","Ajmer","Udaipur","Bhilwara","Alwar","Sikar","Bharatpur","Tonk","Chittorgarh"],
  "Sikkim":               ["Gangtok","Namchi","Mangan"],
  "Tamil Nadu":           ["Chennai","Coimbatore","Madurai","Tiruchirappalli","Salem","Tirunelveli","Tiruppur","Vellore","Erode","Thoothukudi","Thanjavur","Dindigul"],
  "Telangana":            ["Hyderabad","Warangal","Nizamabad","Karimnagar","Khammam","Ramagundam","Mahbubnagar","Nalgonda","Siddipet"],
  "Tripura":              ["Agartala","Udaipur","Dharmanagar"],
  "Uttar Pradesh":        ["Lucknow","Kanpur","Ghaziabad","Agra","Meerut","Varanasi","Allahabad","Bareilly","Aligarh","Noida","Mathura","Moradabad","Saharanpur","Gorakhpur","Firozabad","Loni","Jhansi","Muzaffarnagar"],
  "Uttarakhand":          ["Dehradun","Haridwar","Roorkee","Haldwani","Rishikesh","Nainital","Rudrapur","Kashipur"],
  "West Bengal":          ["Kolkata","Asansol","Siliguri","Durgapur","Bardhaman","Malda","Barasat","Habra","Jalpaiguri","Kharagpur","Howrah"],
  "Delhi":                ["Central Delhi","New Delhi","Dwarka","Rohini","Janakpuri","Karol Bagh","Connaught Place","Saket","Lajpat Nagar","Mayur Vihar","Preet Vihar","Vasant Kunj","Pitampura","Shahdara","Gurgaon (Delhi-NCR)","Noida (Delhi-NCR)","Faridabad (Delhi-NCR)"],
  "Jammu & Kashmir":      ["Srinagar","Jammu","Anantnag","Baramulla","Sopore","Kathua"],
  "Ladakh":               ["Leh","Kargil"],
  "Puducherry":           ["Puducherry","Karaikal","Yanam"],
  "Chandigarh":           ["Chandigarh","Mohali","Panchkula"],
  "Andaman & Nicobar":    ["Port Blair"],
  "Lakshadweep":          ["Kavaratti"],
  "Dadra & Nagar Haveli": ["Silvassa"],
};

export const COPY_SECTIONS = [
  { key: "google",    icon: "🔵", label: "Google Search Ads",         color: "#3b82f6" },
  { key: "instagram", icon: "🟣", label: "Instagram Reel + Caption",  color: "#7c3aed" },
  { key: "linkedin",  icon: "🔷", label: "LinkedIn Organic Post",     color: "#3b82f6" },
  { key: "inmail",    icon: "📩", label: "LinkedIn InMail / Cold DM", color: "#3b82f6" },
  { key: "email",     icon: "📧", label: "Cold Email Template",       color: "#3b82f6" },
  { key: "whatsapp",  icon: "💬", label: "WhatsApp Outreach",         color: "#3b82f6" },
];
