name: Cron - cleanup-news

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/_run-cron.yml
    with:
      slug: cleanup-news
    secrets: inherit
