export const FAQS = [
  { q: 'What technologies does your team use?',                  a: 'Our primary stack is Next.js, React, TypeScript, and Node.js for web platforms; Flutter and React Native for mobile. Backend infrastructure runs on PostgreSQL, Redis, and cloud providers (AWS, GCP, Vercel) selected per project requirements.' },
  { q: 'How do you handle project management and communication?', a: 'We run two-week sprints with weekly video standups, shared project dashboards, and async Slack channels. You receive a working demo at the end of every sprint and can reprioritize features at sprint boundaries.' },
  { q: 'What does your testing process look like?',              a: 'Every feature is covered by automated unit and integration tests before reaching staging. We then run manual QA, accessibility checks, and performance benchmarking. Security-sensitive applications receive a dedicated penetration testing review before launch.' },
  { q: 'Do you provide post-launch support?',                    a: 'Yes. All projects include a 30-day post-launch support window at no additional cost. Beyond that, we offer monthly retainer agreements for ongoing maintenance, feature development, and infrastructure monitoring.' },
  { q: 'Can you take over and modernize an existing codebase?',  a: 'Absolutely. We conduct a full code audit first, identify technical debt and security risks, then propose a phased modernization roadmap. We maintain existing functionality throughout the refactor with zero customer-facing downtime.' },
  { q: 'Do you offer cloud-native software development?',        a: 'Yes. We design applications for containerized, auto-scaling infrastructure on AWS, GCP, or Vercel from day one, rather than retrofitting cloud architecture later. This means your software handles traffic spikes and scales cost-effectively as you grow.' },
  { q: 'Can you build a SaaS product for us as a SaaS development company?', a: 'Yes, SaaS platforms are a core part of what we build. We handle multi-tenant architecture, subscription billing, role-based access, and usage analytics from the ground up so the product is ready for real customers, not just a demo.' },
  { q: 'How much does custom software development cost?',        a: 'A focused internal tool typically starts around $8,000 to $15,000, while a full multi-module enterprise platform can run $40,000 and up. Cost depends on scope, integrations, and team size, and we give you a fixed estimate after discovery, not a vague range.' },
  { q: 'How long does it take to build custom software?',        a: 'A single-purpose tool takes 6 to 10 weeks. A larger enterprise system with multiple modules and integrations typically takes 4 to 8 months. We break the timeline into sprint milestones so you see working software throughout, not just at the end.' },
  { q: 'What is the difference between custom software and off-the-shelf software?', a: 'Off-the-shelf software is built for the average user across thousands of companies, so you adapt your workflow to fit the tool. Custom software is built around your exact processes, data, and integrations, which usually means better efficiency long-term but a higher upfront investment.' },
]
